In [13]:
%useLatestDescriptors
%use dataframe
%use kandy

In [14]:
val iris = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/iris.csv").shuffle()

In [15]:
iris.head()

sepal_length,sepal_width,petal_length,petal_width,species
5.500000,3.500000,1.300000,0.200000,setosa
5.000000,2.000000,3.500000,1.000000,versicolor
7.700000,2.600000,6.900000,2.300000,virginica
5.500000,4.200000,1.400000,0.200000,setosa
5.100000,3.400000,1.500000,0.200000,setosa

In [16]:
iris.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sepal_length,Double,150,35,0,5.000000,10,5.843333,0.828066,4.300000,5.800000,7.900000
sepal_width,Double,150,23,0,3.000000,26,3.054000,0.433594,2.000000,3.000000,4.400000
petal_length,Double,150,43,0,1.500000,14,3.758667,1.764420,1.000000,4.350000,6.900000
petal_width,Double,150,22,0,0.200000,28,1.198667,0.763161,0.100000,1.300000,2.500000
species,String,150,3,0,setosa,50,null,null,setosa,versicolor,virginica

In [17]:
iris.plot {
    layout {
        title ="IRIS Sepal Scatter Plot"
        size = 800 to 600
    }
    points {
        x(sepal_length)
        y(sepal_width)
        symbol(species)
        color(species)
    }
}

In [18]:
iris.plot {
    layout {
        title ="IRIS Petal Scatter Plot"
        size = 800 to 600
    }
    points {
        x(petal_length)
        y(petal_width)
        symbol(species)
        color(species)
    }
}

In [41]:
fun getDummies(colunmName: DataColumn<String>):DataFrame<Any?>{
    return colunmName.map {
            val list = mutableListOf<Boolean>()
            colunmName.distinct().forEach {item ->
                list.add( it.equals(item))
            }
            list
        }.toDataFrame()
}

In [42]:
val specieDummies = getDummies(iris.species)

In [43]:
val irisDf = iris.add(
    specieDummies.split{ species }.into { "specie_$it" }
)
irisDf.head()

sepal_length,sepal_width,petal_length,petal_width,species,specie_1,specie_2,specie_3
5.500000,3.500000,1.300000,0.200000,setosa,true,false,false
5.000000,2.000000,3.500000,1.000000,versicolor,false,true,false
7.700000,2.600000,6.900000,2.300000,virginica,false,false,true
5.500000,4.200000,1.400000,0.200000,setosa,true,false,false
5.100000,3.400000,1.500000,0.200000,setosa,true,false,false

In [22]:
val data =  irisDf.select { sepal_length and sepal_width and petal_length and petal_width }
    .map {
        it.values()
    }

In [23]:
val col = data[0].size
val row = data.size
val irisMatrix = Array(row) { DoubleArray(col) }

var i = 0
for (r in 0 until row) {
    for (c in 0 until col) {
        irisMatrix[r][c] = data[r][c] as Double
    }
}

In [24]:
val target =  irisDf.select { specie_1 and specie_2 and specie_3 }
    .map {
        it.values()
    }