In [18]:
%use kandy
%use dataframe
%use lets-plot

In [177]:
val url = "http://192.168.35.107:7788/khnp/wastewater"
val df = DataFrame.readJson(url)
df.head(5)

time,genName,tm001,tm001_time,tm002,tm002_time
2026-04-22 11:21,KR,0.0,2026-04-22 11:20,7.300000190734863,2026-04-22 11:20
2026-04-22 11:21,WS,40.8,2026-04-22 11:20,7.1,2026-04-22 11:20
2026-04-22 11:21,YK,0,2026-03-30 06:58,0,2026-03-30 06:58
2026-04-22 11:24,KR,0.0,2026-04-22 11:23,7.300000190734863,2026-04-22 11:23
2026-04-22 11:24,WS,40.8,2026-04-22 11:24,7.1,2026-04-22 11:24

In [178]:
import kotlin.math.round

val convertValueDf = df.convert { tm001 and tm002 }.with {
    val value = it?.toString()?.toDoubleOrNull() ?: 0.0
    round(value * 10) / 10.0
}
convertValueDf.head(5)

time,genName,tm001,tm001_time,tm002,tm002_time
2026-04-22 11:21,KR,0.000000,2026-04-22 11:20,7.300000,2026-04-22 11:20
2026-04-22 11:21,WS,40.800000,2026-04-22 11:20,7.100000,2026-04-22 11:20
2026-04-22 11:21,YK,0.000000,2026-03-30 06:58,0.000000,2026-03-30 06:58
2026-04-22 11:24,KR,0.000000,2026-04-22 11:23,7.300000,2026-04-22 11:23
2026-04-22 11:24,WS,40.800000,2026-04-22 11:24,7.100000,2026-04-22 11:24

In [179]:
import kotlinx.datetime.*
import kotlin.time.Duration.Companion.minutes

val convertTimeDf = convertValueDf.convert {
    time and tm001_time and tm002_time
}.with { 
    LocalDateTime.parse(it.toString().replace(" ", "T")).toInstant(TimeZone.UTC)
}

convertTimeDf.head(5)

time,genName,tm001,tm001_time,tm002,tm002_time
2026-04-22T11:21:00Z,KR,0.000000,2026-04-22T11:20:00Z,7.300000,2026-04-22T11:20:00Z
2026-04-22T11:21:00Z,WS,40.800000,2026-04-22T11:20:00Z,7.100000,2026-04-22T11:20:00Z
2026-04-22T11:21:00Z,YK,0.000000,2026-03-30T06:58:00Z,0.000000,2026-03-30T06:58:00Z
2026-04-22T11:24:00Z,KR,0.000000,2026-04-22T11:23:00Z,7.300000,2026-04-22T11:23:00Z
2026-04-22T11:24:00Z,WS,40.800000,2026-04-22T11:24:00Z,7.100000,2026-04-22T11:24:00Z

In [182]:
val checkTime = 10.minutes

val finalDf = convertTimeDf.filter {
    (time - tm001_time).absoluteValue <= checkTime &&
    (time - tm002_time).absoluteValue <= checkTime 
}
finalDf.head(5)

time,genName,tm001,tm001_time,tm002,tm002_time
2026-04-22T11:21:00Z,KR,0.000000,2026-04-22T11:20:00Z,7.300000,2026-04-22T11:20:00Z
2026-04-22T11:21:00Z,WS,40.800000,2026-04-22T11:20:00Z,7.100000,2026-04-22T11:20:00Z
2026-04-22T11:24:00Z,KR,0.000000,2026-04-22T11:23:00Z,7.300000,2026-04-22T11:23:00Z
2026-04-22T11:24:00Z,WS,40.800000,2026-04-22T11:24:00Z,7.100000,2026-04-22T11:24:00Z
2026-04-22T11:30:00Z,KR,0.000000,2026-04-22T11:29:00Z,7.300000,2026-04-22T11:29:00Z

In [183]:
//letsPlot( finalDf.filter{ time >= "2026-04-21 22:00" }.toMap() ) +
letsPlot( finalDf.toMap() ) +
labs( title = "분단위 실시간 폐수 수질현황", y="Wastewater Quality (PH)", x="수집시간", color="발전소") +     
geomPoint( alpha = 0.6){
    x = "time";
    y = "tm002";
    color="genName";
    size="tm001";
} +
scaleYContinuous(limits=Pair(5.0,9.0)) +
// %Y: 년, %m: 월, %d: 일, %H: 시, %M: 분
scaleXDateTime(
    format = "%m-%d %H:%M" 
) +
scaleSize(range=Pair(0, 15), name="유량") +
theme(
    axisTextX= elementText( angle=45, hjust = 1.0),
) +    
ggsize( width = 2400, height = 450)

In [167]:
val url = "http://192.168.35.107:7788/khnp/thermalwastewater"
val df = DataFrame.readJson(url)
df.head(5)

time,genName,rm001,rm001_time,rm002,rm002_time,rm005,rm005_time,rm006,rm006_time
2026-04-22 11:21,KR,0,2026-02-04 18:37,0,2026-02-04 18:37,0,2026-02-04 18:37,0,2026-02-04 18:37
2026-04-22 11:21,UJ,10.3,2026-04-22 11:20,33.6,2026-04-22 11:21,15.5,2026-04-22 11:21,33.4,2026-04-22 11:21
2026-04-22 11:21,WS,14.0,2026-04-22 11:20,34.20000076293945,2026-04-22 11:20,14.0,2026-04-22 11:20,32.900001525878906,2026-04-22 11:20
2026-04-22 11:21,YK,16.100000381469727,2026-04-22 11:10,32.5,2026-04-22 11:10,23.0,2026-04-22 11:10,32.400001525878906,2026-04-22 11:10
2026-04-22 11:24,KR,0,2026-02-04 18:37,0,2026-02-04 18:37,0,2026-02-04 18:37,0,2026-02-04 18:37

In [168]:
import kotlinx.datetime.*
import kotlin.time.Duration.Companion.minutes

val convertedDf = df.convert {
    time and rm001_time and rm002_time and rm005_time and rm006_time
}.with { 
    LocalDateTime.parse(it.toString().replace(" ", "T")).toInstant(TimeZone.UTC)
}

convertedDf.head(5)

time,genName,rm001,rm001_time,rm002,rm002_time,rm005,rm005_time,rm006,rm006_time
2026-04-22T11:21:00Z,KR,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z
2026-04-22T11:21:00Z,UJ,10.3,2026-04-22T11:20:00Z,33.6,2026-04-22T11:21:00Z,15.5,2026-04-22T11:21:00Z,33.4,2026-04-22T11:21:00Z
2026-04-22T11:21:00Z,WS,14.0,2026-04-22T11:20:00Z,34.20000076293945,2026-04-22T11:20:00Z,14.0,2026-04-22T11:20:00Z,32.900001525878906,2026-04-22T11:20:00Z
2026-04-22T11:21:00Z,YK,16.100000381469727,2026-04-22T11:10:00Z,32.5,2026-04-22T11:10:00Z,23.0,2026-04-22T11:10:00Z,32.400001525878906,2026-04-22T11:10:00Z
2026-04-22T11:24:00Z,KR,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z,0,2026-02-04T18:37:00Z

In [169]:
val checkTime = 20.minutes

val finalDf = convertedDf.filter {
    (time - rm001_time).absoluteValue <= checkTime &&
    (time - rm002_time).absoluteValue <= checkTime &&
    (time - rm005_time).absoluteValue <= checkTime &&
    (time - rm006_time).absoluteValue <= checkTime
}
finalDf.head(5)

time,genName,rm001,rm001_time,rm002,rm002_time,rm005,rm005_time,rm006,rm006_time
2026-04-22T11:21:00Z,UJ,10.3,2026-04-22T11:20:00Z,33.6,2026-04-22T11:21:00Z,15.5,2026-04-22T11:21:00Z,33.4,2026-04-22T11:21:00Z
2026-04-22T11:21:00Z,WS,14.0,2026-04-22T11:20:00Z,34.20000076293945,2026-04-22T11:20:00Z,14.0,2026-04-22T11:20:00Z,32.900001525878906,2026-04-22T11:20:00Z
2026-04-22T11:21:00Z,YK,16.100000381469727,2026-04-22T11:10:00Z,32.5,2026-04-22T11:10:00Z,23.0,2026-04-22T11:10:00Z,32.400001525878906,2026-04-22T11:10:00Z
2026-04-22T11:24:00Z,UJ,10.3,2026-04-22T11:24:00Z,33.7,2026-04-22T11:24:00Z,15.6,2026-04-22T11:24:00Z,33.2,2026-04-22T11:24:00Z
2026-04-22T11:24:00Z,WS,14.0,2026-04-22T11:20:00Z,34.20000076293945,2026-04-22T11:20:00Z,14.0,2026-04-22T11:20:00Z,32.900001525878906,2026-04-22T11:20:00Z

In [170]:
val data = finalDf.select{ time and genName and rm001 and rm005}
data.describe()

name,type,count,unique,nulls,top,freq,min,median,max
time,kotlinx.datetime.Instant,126,42,0,2026-04-22T11:21:00Z,3,2026-04-22T11:21:00Z,2026-04-22T13:14:00Z,2026-04-22T15:12:00Z
genName,String,126,3,0,UJ,42,UJ,WS,YK
rm001,String,126,28,0,14.3,22,10.0,14.3,9.9
rm005,String,126,30,0,24.0,11,14.0,15.2,24.2

In [171]:
import kotlin.math.round

val data = finalDf.select{ time and genName and rm001 and rm005}
    .convert{ rm001 and rm005}.with {
        val value = it?.toString()?.toDoubleOrNull() ?: 0.0
        round(value * 10) / 10.0
}.toMap()


letsPlot(data) +
geomRibbon(
    alpha = 0.2,
          // 툴팁 설정 추가
    tooltips = layerTooltips()
        .title("@genName")              // 툴팁 제목에 발전소 이름 표시
        .line("시간|@time")             // '라벨|값' 형식으로 표시
        .line("취수 수온|@rm001 °C")
        .line("배수 수온|@rm005 °C")
        .format("@time", "%m-%d %H:%M") // 시간 형식 지정
        .format("@rm001", ".1f")        // 소수점 첫째 자리까지 표시
        .format("@rm005", ".1f")
          ){
    x="time"
    ymin = "rm001"
    ymax = "rm005"
    fill = "genName"
} +
scaleYContinuous(limits=Pair(5.0,25.0)) +    
scaleXDateTime(  
    format = "%m-%d %H:%M" ,
            // 데이터의 'time' 컬럼에 있는 모든 값을 그리드 위치로 지정
    breaks = data["time"] as List<*> 
) +
labs( title = "발전소별 실시간 취수/배수 수온 현황", y="수온(°C)", x="수집시간", fill="발전소") +  
theme(
    axisTextX= elementText( angle=45),
    // X축 주요 그리드 선 설정 (색상, 두께 등)
        panelGridMajorX = elementLine(color = "#e0e0e0", size = 0.5),

   
) +
ggsize(2400, 600)