In [1]:
%useLatestDescriptors
%use dataframe, kandy
%use kandy-geo
%use lets-plot
%use lets-plot-gt

In [4]:
val df_ondeday = DataFrame.readJson("http://127.0.0.1:7788/nifs/seawaterinfo/oneday")
df_ondeday.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3402,44,0,bgj8a,144,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3402,44,0,기장,144,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3402,48,0,2025-03-22 09:30:00,71,null,null,2025-03-22 09:30:00,2025-03-22 21:30:00,2025-03-23 09:00:00
obs_lay,String,3402,3,0,1,2108,null,null,1,1,3
wtr_tmp,String,3402,86,0,9.1,173,null,null,10,7.5,9.9
dox,String?,3402,50,2682,10.1,47,null,null,10,12.3,9.9
sal,String?,3402,6,3306,34.8,47,null,null,32.4,32.6,34.8
gru_nam,String,3402,3,0,남해,1774,null,null,남해,남해,서해
lon,Double,3402,44,0,35.187000,144,35.530488,1.373381,33.310400,34.808200,38.368100
lat,Double,3402,44,0,129.227000,144,127.620301,1.172342,124.729500,127.122800,129.549700

In [8]:
import kotlinx.datetime.format.FormatStringsInDatetimeFormats
import kotlinx.datetime.format.byUnicodePattern

@OptIn(FormatStringsInDatetimeFormats::class)
val dateTimeFormat = LocalDateTime.Format {
    byUnicodePattern("yyyy-MM-dd HH:mm:ss")
}

val df_East = df_ondeday.filter {
        gru_nam.equals("동해") and obs_lay.equals("1")
    }.add {
        "hour" from obs_datetime.map {
            dateTimeFormat.parse(it).hour
        }
    }.select{
        sta_nam_kor and wtr_tmp and obs_datetime  and gru_nam and sta_cde  and "hour"
    }.convert { wtr_tmp }.with{ it.toFloat()}

In [13]:
df_East
    // .convert{ obs_tim }.with{ LocalTime.parse(it) }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 2600 to 600
        }

        x(obs_datetime) { axis.name = "관측일시"}
        y(wtr_tmp) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(sta_nam_kor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [9]:
df_East
    .groupBy { sta_cde and sta_nam_kor and hour }
    .aggregate {
        min{wtr_tmp} into "min"
        max{wtr_tmp} into "max"
        mean{wtr_tmp} into "mean"
        min{obs_datetime} into "time"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 2600 to 1200
        }

        ribbon {
            x("time") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("sta_nam_kor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(sta_nam_kor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("time")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..12.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(sta_nam_kor)
        }
    }

In [11]:
df_East
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [14]:
val df_current = DataFrame.readJson("http://127.0.0.1:7788/nifs/seawaterinfo/current")
df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,71,44,0,bgj8a,3,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,71,44,0,기장,3,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,71,1,0,2025-03-23 09:00:00,71,null,null,2025-03-23 09:00:00,2025-03-23 09:00:00,2025-03-23 09:00:00
obs_lay,String,71,3,0,1,44,null,null,1,1,3
wtr_tmp,String,71,40,0,9.1,5,null,null,10,7.9,9.9
dox,String?,71,14,56,9.5,2,null,null,10,12.3,9.9
sal,String?,71,3,69,34.8,1,null,null,32.5,32.5,34.8
gru_nam,String,71,3,0,남해,37,null,null,남해,남해,서해
lon,Double,71,44,0,35.187000,3,35.531207,1.382445,33.310400,34.808200,38.368100
lat,Double,71,44,0,129.227000,3,127.618854,1.180469,124.729500,127.122800,129.549700

In [15]:
df_current
    .filter { gru_nam.equals("동해") }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [46]:
val data = df_current.filter{ gru_nam.equals("동해")}
    .select{sta_nam_kor  and obs_lay and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .convert {obs_lay }.with {
        when(obs_lay) {
        "1" -> "표층"
        "2" -> "중층"
        "3" -> "저층"
        else -> {""}
        } }

In [47]:
data.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,19,7,0,기장,3,null,null,강릉,기장,영덕
obs_lay,String,19,3,0,표층,7,null,null,저층,중층,표층
wtr_tmp,Float,19,15,0,11.500000,3,8.994737,2.194304,5.500000,10.300000,11.500000

In [48]:
letsPlot(data.toMap()) {  x = "sta_nam_kor" } +
    geomBar(position = positionDodge(), alpha = 0.5){
        fill = "obs_lay"
        weight = "wtr_tmp" } +
    labs( title="Korea EastSea 수온 정보", y="온도 °C", x="관측지점", fill="관측수심") +
    scaleYContinuous(limits=Pair(0,15) ) +
    ggsize( width = 600, height = 300)

In [49]:
data class SeawaterInformationByObservationPoint(
    val sta_cde: String,
    val sta_nam_kor: String,
    val obs_datetime: String,
    val obs_lay: String,
    val wtr_tmp: String,
    val dox: String?,
    val sal: String?,
    val gru_nam: String,
    val lon: Double,
    val lat: Double,
)

val sta_nam_kor = mutableListOf<String>()
val obs_lay = mutableListOf<String>()
val wtr_tmp = mutableListOf<Float>()

df_current.toListOf<SeawaterInformationByObservationPoint>().forEach {
    sta_nam_kor.add(it.sta_nam_kor)
    obs_lay.add(
        when(it.obs_lay) {
            "1" -> "표층"
            "2" -> "중층"
            "3" -> "저층"
            else -> {""}
        }
    )
    wtr_tmp.add(it.wtr_tmp.toFloat())
}

val data2 = mapOf<String, List<Any>>( "관측지점" to sta_nam_kor, "관측수심" to obs_lay, "온도" to wtr_tmp  )

In [50]:
letsPlot(data2) { x = "관측지점" } +
    geomBar(position = positionDodge(), alpha = 0.5){
        fill = "관측수심"
        weight = "온도" } +
    labs( title="Korea Sea Water Quality", y="온도 °C") +
    scaleYContinuous(limits=Pair(0,15) ) +
    ggsize( width = 1200, height = 300)

In [80]:
val sta_nam_kor = mutableListOf<String>()
val wtr_tmp = mutableListOf<Float>()
val obs_datetime = mutableListOf<String>()

df_ondeday.filter {  gru_nam.equals("동해") and obs_lay.equals("1") }.toListOf<SeawaterInformationByObservationPoint>().forEach {
    sta_nam_kor.add(it.sta_nam_kor)
    obs_datetime.add(it.obs_datetime)
    wtr_tmp.add(it.wtr_tmp.toFloat())
}

val data3 = mapOf<String, List<Any>>( "관측지점" to sta_nam_kor, "관측시간" to obs_datetime, "온도" to wtr_tmp  )

In [174]:
letsPlot(data3) +
        geomLine( ) { x="관측시간"; y="온도"; color="관측지점"} +
        labs( title="Korea Sea Water Quality", y="온도 °C") +
        scaleYContinuous(limits=Pair(0,15) ) +
        ggsize( width = 1200, height = 600)

In [105]:
df_ondeday.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3402,44,0,bgj8a,144,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3402,44,0,기장,144,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3402,48,0,2025-03-22 09:30:00,71,null,null,2025-03-22 09:30:00,2025-03-22 21:30:00,2025-03-23 09:00:00
obs_lay,String,3402,3,0,1,2108,null,null,1,1,3
wtr_tmp,String,3402,86,0,9.1,173,null,null,10,7.5,9.9
dox,String?,3402,50,2682,10.1,47,null,null,10,12.3,9.9
sal,String?,3402,6,3306,34.8,47,null,null,32.4,32.6,34.8
gru_nam,String,3402,3,0,남해,1774,null,null,남해,남해,서해
lon,Double,3402,44,0,35.187000,144,35.530488,1.373381,33.310400,34.808200,38.368100
lat,Double,3402,44,0,129.227000,144,127.620301,1.172342,124.729500,127.122800,129.549700

In [165]:
val data_stat = df_ondeday.filter {  gru_nam.equals("동해") and obs_lay.equals("1") }
    .convert{wtr_tmp}.with{it.toFloat()}.toMap()

In [171]:
val sta_nam_korByMiddle = asDiscrete("sta_nam_kor", orderBy = "..middle..", order = 1)

letsPlot(
    data_stat
) { y = "wtr_tmp"} +
scaleColorViridis(option = "C", end = 0.8) +
ggsize(700, 400) +
geomBoxplot(){ x=sta_nam_korByMiddle ; color = "..middle.."} +
labs(y="온도 °C", x="관측지점", color ="온도 °C")