In [1]:
%useLatestDescriptors
%use dataframe, kandy
%use kandy-geo
%use lets-plot
%use lets-plot-gt

In [2]:
val df_ondeday = DataFrame.readJson("http://127.0.0.1:7788/nifs/seawaterinfo/oneday")
df_ondeday.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3303,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3303,44,0,기장,141,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3303,47,0,2025-03-25 11:00:00,71,null,null,2025-03-25 11:00:00,2025-03-25 22:30:00,2025-03-26 10:00:00
obs_lay,String,3303,3,0,1,2050,null,null,1,1,3
wtr_tmp,String,3303,89,0,10.5,194,null,null,10,5.6,9.9
dox,String?,3303,53,2604,9.7,63,null,null,10,12.7,9.9
sal,String?,3303,8,3209,34.8,39,null,null,32.3,32.5,34.8
gru_nam,String,3303,3,0,남해,1726,null,null,남해,남해,서해
lon,Double,3303,44,0,35.187000,141,35.524863,1.372351,33.310400,34.808200,38.368100
lat,Double,3303,44,0,129.227000,141,127.614010,1.171086,124.729500,127.122800,129.549700

In [134]:
import kotlinx.datetime.format.FormatStringsInDatetimeFormats
import kotlinx.datetime.format.byUnicodePattern

@OptIn(FormatStringsInDatetimeFormats::class)
val dateTimeFormat = LocalDateTime.Format {
    byUnicodePattern("yyyy-MM-dd HH:mm:ss")
}

val df_OneDay = df_ondeday.add {
    "datetime" from obs_datetime.map {
        dateTimeFormatInput.parse(it).format(dateTimeFormatOuput)
    }
    "hour" from obs_datetime.map {
        dateTimeFormat.parse(it).hour
    }

}.convert { wtr_tmp }.with{ it.toFloat()}

In [98]:
import kotlinx.datetime.format.FormatStringsInDatetimeFormats
import kotlinx.datetime.format.byUnicodePattern

@OptIn(FormatStringsInDatetimeFormats::class)
val dateTimeFormatInput = LocalDateTime.Format { byUnicodePattern("yyyy-MM-dd HH:mm:ss") }
val dateTimeFormatOuput = LocalDateTime.Format { byUnicodePattern("yy/MM/dd HH:mm") }

val df_East = df_ondeday.filter {
        gru_nam.equals("동해") and obs_lay.equals("1")
    }.add {
        "hour" from obs_datetime.map {
            dateTimeFormat.parse(it).hour
        }
        "datetime" from obs_datetime.map {
            dateTimeFormatInput.parse(it).format(dateTimeFormatOuput)
        }

    }.select{
        sta_nam_kor and wtr_tmp and obs_datetime  and gru_nam and sta_cde  and "hour" and "datetime"
    }.convert { wtr_tmp }.with{ it.toFloat()}

In [75]:
df_East.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,324,7,0,기장,47,null,null,강릉,기장,영덕
wtr_tmp,Float,324,40,0,10.400000,24,9.979321,1.786024,6.600000,10.600000,12.200000
obs_datetime,String,324,47,0,2025-03-25 11:00:00,7,null,null,2025-03-25 11:00:00,2025-03-25 22:30:00,2025-03-26 10:00:00
gru_nam,String,324,1,0,동해,324,null,null,동해,동해,동해
sta_cde,String,324,7,0,bgj8a,47,null,null,bgj8a,byd8a,fghe8
hour,Int,324,24,0,11,14,11.552469,6.972327,0,12,23
datetime,String,324,47,0,25/03/25 11:00,7,null,null,25/03/25 11:00,25/03/25 22:30,25/03/26 10:00

In [114]:
import org.jetbrains.letsPlot.commons.intern.math.rotateAround

df_East
    // .convert{ obs_tim }.with{ LocalTime.parse(it) }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 2600 to 600
        }
        x( datetime) { axis.name = "관측일시"  }
        y(wtr_tmp) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0

        line{
            color(sta_nam_kor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [77]:
df_East
    .groupBy { sta_cde and sta_nam_kor and hour }
    .aggregate {
        min{wtr_tmp} into "min"
        max{wtr_tmp} into "max"
        mean{wtr_tmp} into "mean"
        min{datetime} into "time"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 2600 to 1200
        }

        ribbon {
            x("time") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("sta_nam_kor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(sta_nam_kor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("time")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..12.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(sta_nam_kor)
        }
    }

In [78]:
df_East
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [79]:
val df_current = DataFrame.readJson("http://127.0.0.1:7788/nifs/seawaterinfo/current")
df_current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,68,43,0,bgj8a,3,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,68,43,0,기장,3,null,null,강릉,완도 감목,해남 화산
obs_datetime,String,68,1,0,2025-03-26 11:00:00,68,null,null,2025-03-26 11:00:00,2025-03-26 11:00:00,2025-03-26 11:00:00
obs_lay,String,68,3,0,1,43,null,null,1,1,3
wtr_tmp,String,68,41,0,9.8,4,null,null,10,6.2,9.9
dox,String?,68,14,53,10,2,null,null,10,12.8,9.7
sal,String?,68,3,66,34.8,1,null,null,32.4,32.4,34.8
gru_nam,String,68,3,0,남해,37,null,null,남해,남해,서해
lon,Double,68,43,0,35.187000,3,35.453071,1.360176,33.310400,34.803000,38.368100
lat,Double,68,43,0,129.227000,3,127.544125,1.149682,124.729500,127.074550,129.549700

In [106]:
df_current
    .filter { gru_nam.equals("동해") }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }

            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [81]:
val data = df_current.filter{ gru_nam.equals("동해")}
    .select{sta_nam_kor  and obs_lay and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .convert {obs_lay }.with {
        when(obs_lay) {
        "1" -> "표층"
        "2" -> "중층"
        "3" -> "저층"
        else -> {""}
        } }

In [82]:
data.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,16,6,0,기장,3,null,null,강릉,기장,영덕
obs_lay,String,16,3,0,표층,6,null,null,저층,중층,표층
wtr_tmp,Float,16,14,0,11.600000,2,9.037500,2.085785,5.700000,9.950001,11.700000

In [83]:
letsPlot(data.toMap()) {  x = "sta_nam_kor" } +
    geomBar(position = positionDodge(), alpha = 0.5){
        fill = "obs_lay"
        weight = "wtr_tmp" } +
    labs( title="Korea EastSea 수온 정보", y="온도 °C", x="관측지점", fill="관측수심") +
    scaleYContinuous(limits=Pair(0,15) ) +
    ggsize( width = 600, height = 300)

In [85]:
data class SeawaterInformationByObservationPoint(
    val sta_cde: String,
    val sta_nam_kor: String,
    val obs_datetime: String,
    val obs_lay: String,
    val wtr_tmp: String,
    val dox: String?,
    val sal: String?,
    val gru_nam: String,
    val lon: Double,
    val lat: Double
)
val sta_nam_kor = mutableListOf<String>()
val obs_lay = mutableListOf<String>()
val wtr_tmp = mutableListOf<Float>()

df_current.toListOf<SeawaterInformationByObservationPoint>().forEach {
    sta_nam_kor.add(it.sta_nam_kor)
    obs_lay.add(
        when(it.obs_lay) {
            "1" -> "표층"
            "2" -> "중층"
            "3" -> "저층"
            else -> {""}
        }
    )
    wtr_tmp.add(it.wtr_tmp.toFloat())
}

val data2 = mapOf<String, List<Any>>( "관측지점" to sta_nam_kor, "관측수심" to obs_lay, "온도" to wtr_tmp  )

In [105]:
letsPlot(data2) { x = "관측지점" } +
    geomBar(position = positionDodge(), alpha = 0.5){
        fill = "관측수심"
        weight = "온도" } +
    labs( title="Korea Sea Water Quality", y="온도 °C") +
    scaleYContinuous(limits=Pair(0,15) ) +
        theme(
            axisTextX= elementText( angle=45),
        ) +
    ggsize( width = 1200, height = 300)

In [87]:
df_OneDay.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3303,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3303,44,0,기장,141,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3303,47,0,2025-03-25 11:00:00,71,null,null,2025-03-25 11:00:00,2025-03-25 22:30:00,2025-03-26 10:00:00
obs_lay,String,3303,3,0,1,2050,null,null,1,1,3
wtr_tmp,Float,3303,89,0,10.500000,194,9.712171,1.626482,4.800000,9.900000,15.100000
dox,String?,3303,53,2604,9.7,63,null,null,10,12.7,9.9
sal,String?,3303,8,3209,34.8,39,null,null,32.3,32.5,34.8
gru_nam,String,3303,3,0,남해,1726,null,null,남해,남해,서해
lon,Double,3303,44,0,35.187000,141,35.524863,1.372351,33.310400,34.808200,38.368100
lat,Double,3303,44,0,129.227000,141,127.614010,1.171086,124.729500,127.122800,129.549700
datetime,kotlinx.datetime.LocalDateTime,3303,47,0,2025-03-25T11:00,71,null,null,2025-03-25T11:00,2025-03-25T22:30,2025-03-26T10:00

In [90]:
data class SeawaterInformation(
    val sta_cde: String,
    val sta_nam_kor: String,
    val obs_datetime: String,
    val obs_lay: String,
    val wtr_tmp: String,
    val dox: String?,
    val sal: String?,
    val gru_nam: String,
    val lon: Double,
    val lat: Double,
    val datetime: String
)

val sta_nam_kor = mutableListOf<String>()
val wtr_tmp = mutableListOf<Float>()
val obs_datetime = mutableListOf<String>()
val datetime = mutableListOf<String>()

df_OneDay.filter {  gru_nam.equals("동해") and obs_lay.equals("1") }.toListOf<SeawaterInformation>().forEach {
    sta_nam_kor.add(it.sta_nam_kor)
    obs_datetime.add(it.obs_datetime)
    datetime.add(it.datetime )
    wtr_tmp.add(it.wtr_tmp.toFloat())
}

val data3 = mapOf<String, List<Any>>( "관측지점" to sta_nam_kor, "관측시간" to obs_datetime, "온도" to wtr_tmp, "일시" to datetime  )

In [141]:
letsPlot(data3) +
        geomLine( ) { x="일시"; y="온도"; color="관측지점"} +
        labs( title="Korea Sea Water Quality", y="온도 °C") +
        scaleYContinuous(limits=Pair(0,15) ) +
        theme(
            axisTextX= elementText( angle=45),
        ) +
        ggsize( width = 100, height = 600)

In [94]:
df_OneDay.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,3303,44,0,bgj8a,141,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,3303,44,0,기장,141,null,null,강릉,완도 가교,해남 화산
obs_datetime,String,3303,47,0,2025-03-25 11:00:00,71,null,null,2025-03-25 11:00:00,2025-03-25 22:30:00,2025-03-26 10:00:00
obs_lay,String,3303,3,0,1,2050,null,null,1,1,3
wtr_tmp,Float,3303,89,0,10.500000,194,9.712171,1.626482,4.800000,9.900000,15.100000
dox,String?,3303,53,2604,9.7,63,null,null,10,12.7,9.9
sal,String?,3303,8,3209,34.8,39,null,null,32.3,32.5,34.8
gru_nam,String,3303,3,0,남해,1726,null,null,남해,남해,서해
lon,Double,3303,44,0,35.187000,141,35.524863,1.372351,33.310400,34.808200,38.368100
lat,Double,3303,44,0,129.227000,141,127.614010,1.171086,124.729500,127.122800,129.549700
datetime,String,3303,47,0,25/03/25 11:00,71,null,null,25/03/25 11:00,25/03/25 22:30,25/03/26 10:00

In [146]:
val data_stat = df_OneDay.filter { gru_nam.equals("동해") and obs_lay.equals("1") }.toMap()

In [147]:
val sta_nam_korByMiddle = asDiscrete("sta_nam_kor", orderBy = "..middle..", order = 1)

letsPlot(
    data_stat
) { y = "wtr_tmp"} +
scaleColorViridis(option = "C", end = 0.8) +
geomBoxplot(){ x=sta_nam_korByMiddle ; color = "..middle.."} +
labs(y="온도 °C", x="관측지점", color ="온도 °C") +
ggsize( width = 600, height = 400)
//facetWrap(facets="gru_nam") +

In [139]:
val data_Ribbon = df_East.groupBy{ sta_nam_kor and hour}.aggregate {
    wtr_tmp.max() into "max"
    wtr_tmp.min() into "min"
    wtr_tmp.mean().toFloat() into "mean"
    datetime.min() into "datetime"

}.toMap()

In [140]:
letsPlot(data_Ribbon) +
        geomRibbon(alpha = 0.2){
            x="datetime"
            ymin = "min"
            ymax = "max"
            fill = "sta_nam_kor"
        } +
        geomLine( ) {x="datetime"; y="mean"; color="sta_nam_kor"} +
        scaleYContinuous(limits=Pair(10,12.5) ) +
        labs(x="시간", y="수온") +
        theme(
            axisTextX= elementText( angle=45),
        ) +
        ggsize(1200, 800)