In [1]:
%useLatestDescriptors
%use dataframe, kandy
%use kandy-geo

In [92]:
USE {
    dependencies {
        implementation("org.xerial:sqlite-jdbc:3.49.1.0")
        implementation("ch.qos.logback:logback-classic:1.5.12")
    }
}

In [3]:
import java.sql.Connection
import java.sql.DriverManager

In [36]:
Class.forName("org.sqlite.JDBC")
val connection = DriverManager.getConnection("jdbc:sqlite:/Users/unchil/full-stack-task-manager/full-stack-task-manager.sqlite")

In [4]:
import java.time.*
import java.time.format.DateTimeFormatter
import java.text.SimpleDateFormat

In [34]:
val formatter = DateTimeFormatter.ofPattern("YYYY-MM-dd HH:mm:ss")
val now = java.time.LocalDateTime.now()
val prevDay = now.minusHours(24)

print("Current time : ${now.format(formatter)}, Previous time : ${prevDay.format(formatter)}")

Current time : 2025-03-17 10:42:59, Previous time : 2025-03-16 10:42:59

In [47]:
val whereStmt_last24h  = "WHERE obs_datetime > '${prevDay.format(formatter)}' "
val sqlStmt = "SELECT * FROM Observation " + whereStmt_last24h
val df_list = DataFrame.readSqlQuery(connection, sqlStmt)
df_list.describe()

name,type,count,unique,nulls,top,freq,min,median,max
sta_cde,String,2965,44,0,bgj8a,126,bgj8a,fnm5b,wn087
sta_nam_kor,String,2965,44,0,기장,126,강릉,완도 가교,해남 화산
obs_dat,String,2965,2,0,2025-03-17,1555,2025-03-16,2025-03-17,2025-03-17
obs_tim,String,2965,43,0,14:00:00,71,00:00:00,10:00:00,23:30:00
repair_gbn,String,2965,1,0,1,2965,1,1,1
obs_lay,String,2965,3,0,1,1837,1,1,3
wtr_tmp,String,2965,94,0,8.9,139,10,7.8,9.9
dox,String?,2965,44,2339,9.6,46,10,12.2,9.9
sal,String?,2965,5,2881,32.5,42,32.5,32.5,34.9
obs_datetime,String,2965,43,0,2025-03-16 14:00:00,71,2025-03-16 13:30:00,2025-03-17 00:30:00,2025-03-17 10:30:00

In [48]:
val df_code = DataFrame.readSqlTable(connection, "Observatory")
df_code.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,84,84,0,fwdo5,1,null,null,bgj8a,fwdo5,ys002
sta_nam_kor,String,84,80,0,여수,2,null,null,강릉,영광,흑산도 대둔
bld_dat,String,84,64,0,2010-03-14,7,null,null,2003-11-25,2008-07-23,2024-05-13
end_dat,String?,84,38,44,2010-03-15,3,null,null,2005-01-20,2010-03-15,2024-05-25
gru_nam,String,84,3,0,남해,50,null,null,남해,남해,서해
lon,Double,84,84,0,126.736400,1,127.433104,1.137047,124.729500,127.236850,129.813100
lat,Double,84,84,0,34.382500,1,35.182755,1.251893,33.291000,34.741435,38.368100
sur_tmp_yn,String,84,2,0,Y,53,null,null,N,Y,Y
mid_tmp_yn,String,84,2,0,N,61,null,null,N,N,Y
bot_tmp_yn,String,84,2,0,N,75,null,null,N,N,Y
sur_dep,String?,84,11,8,5,48,null,null,1,5,7
mid_dep,String?,84,12,59,6,6,null,null,10,20,9
bot_dep,String?,84,9,71,30,3,null,null,10,25,30
sta_des,String?,84,63,19,태안군청 신규관측소,2,null,null,2020년 7월 4일부로 고성 봉포지역에서 속초 장사항으로 이전설치...,외나로도 남방 국립수산과학원 해양관측부이,포항 구룡포 하정 양식장

In [49]:
val df = df_list.innerJoinWith(df_code.select { sta_cde and gru_nam and lon and lat }) {
    right.sta_cde == sta_cde
}
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_cde,String,2965,44,0,bgj8a,126,null,null,bgj8a,fnm5b,wn087
sta_nam_kor,String,2965,44,0,기장,126,null,null,강릉,완도 가교,해남 화산
obs_dat,String,2965,2,0,2025-03-17,1555,null,null,2025-03-16,2025-03-17,2025-03-17
obs_tim,String,2965,43,0,14:00:00,71,null,null,00:00:00,10:00:00,23:30:00
repair_gbn,String,2965,1,0,1,2965,null,null,1,1,1
obs_lay,String,2965,3,0,1,1837,null,null,1,1,3
wtr_tmp,String,2965,94,0,8.9,139,null,null,10,7.8,9.9
dox,String?,2965,44,2339,9.6,46,null,null,10,12.2,9.9
sal,String?,2965,5,2881,32.5,42,null,null,32.5,32.5,34.9
obs_datetime,String,2965,43,0,2025-03-16 14:00:00,71,null,null,2025-03-16 13:30:00,2025-03-17 00:30:00,2025-03-17 10:30:00
sta_cde1,String,2965,44,0,bgj8a,126,null,null,bgj8a,fnm5b,wn087
gru_nam,String,2965,3,0,남해,1544,null,null,남해,남해,서해
lon,Double,2965,44,0,129.227000,126,127.619747,1.173147,124.729500,127.122800,129.549700
lat,Double,2965,44,0,35.187000,126,35.530720,1.373187,33.310400,34.808200,38.368100

In [59]:
df.filter{ gru_nam.equals("동해") and obs_lay.equals("1")  }
    .select{ sta_cde and sta_nam_kor and wtr_tmp }
    .convert { wtr_tmp }.with{ it.toFloat()}
    .groupBy{sta_cde and sta_nam_kor}
    .sortBy { sta_cde and  sta_nam_kor }
    .plot{
        layout {
            title = "관측지점별 일평균 표층 해수 정보"
            size = 1000 to 600
            //    theme = Theme.HIGH_CONTRAST_DARK
            x.axis {
                name = "관측지점"
            }
            y.axis {
                name = "온도"
                limits = 0.0..20.0
            }
        }

        boxplot("sta_nam_kor", "wtr_tmp") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("sta_nam_kor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }


    }

In [42]:
df.columnNames()

[sta_cde, sta_nam_kor, obs_dat, obs_tim, repair_gbn, obs_lay, wtr_tmp, dox, sal, obs_datetime, sta_cde1, gru_nam, lon, lat]

In [60]:
val df_East = df.filter {
    gru_nam.equals("동해") and obs_lay.equals("1")
}.add {
    "hour" from obs_tim.map {
        LocalTime.parse(it).hour
    }
}.select{
    sta_nam_kor and wtr_tmp and obs_tim  and gru_nam and sta_cde and obs_datetime and "hour"
}.convert { wtr_tmp }.with{ it.toFloat()}


df_East

sta_nam_kor,wtr_tmp,obs_tim,gru_nam,sta_cde,obs_datetime,hour
기장,12.300000,14:00:00,동해,bgj8a,2025-03-16 14:00:00,14
강릉,5.500000,14:00:00,동해,bgna3,2025-03-16 14:00:00,14
삼척,7.400000,14:00:00,동해,bsc87,2025-03-16 14:00:00,14
영덕,11.300000,14:00:00,동해,byd8a,2025-03-16 14:00:00,14
양양,6.900000,14:00:00,동해,byy87,2025-03-16 14:00:00,14
고성 가진,6.400000,14:00:00,동해,fggo3,2025-03-16 14:00:00,14
구룡포 하정,11.000000,14:00:00,동해,fghe8,2025-03-16 14:00:00,14
기장,12.100000,14:30:00,동해,bgj8a,2025-03-16 14:30:00,14
강릉,5.500000,14:30:00,동해,bgna3,2025-03-16 14:30:00,14
삼척,7.300000,14:30:00,동해,bsc87,2025-03-16 14:30:00,14
영덕,11.300000,14:30:00,동해,byd8a,2025-03-16 14:30:00,14
양양,6.900000,14:30:00,동해,byy87,2025-03-16 14:30:00,14
고성 가진,6.500000,14:30:00,동해,fggo3,2025-03-16 14:30:00,14
구룡포 하정,11.000000,14:30:00,동해,fghe8,2025-03-16 14:30:00,14
기장,12.100000,15:00:00,동해,bgj8a,2025-03-16 15:00:00,15
강릉,5.500000,15:00:00,동해,bgna3,2025-03-16 15:00:00,15
삼척,7.200000,15:00:00,동해,bsc87,2025-03-16 15:00:00,15
영덕,11.300000,15:00:00,동해,byd8a,2025-03-16 15:00:00,15
양양,6.900000,15:00:00,동해,byy87,2025-03-16 15:00:00,15
고성 가진,6.600000,15:00:00,동해,fggo3,2025-03-16 15:00:00,15

In [61]:
df_East
    .groupBy { sta_cde and sta_nam_kor and hour }
    .aggregate {
        min{wtr_tmp} into "min"
        max{wtr_tmp} into "max"
        mean{wtr_tmp} into "mean"
        min{obs_datetime} into "time"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 2600 to 1200
        }

        ribbon {
            x("time") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("sta_nam_kor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(sta_nam_kor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("time")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..12.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(sta_nam_kor)
        }
    }

In [62]:
df_East
    .select{  sta_nam_kor and wtr_tmp and obs_datetime   }
   // .convert{ obs_tim }.with{ LocalTime.parse(it) }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 2600 to 600
        }

        x(obs_datetime) { axis.name = "관측일시"}
        y(wtr_tmp) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(sta_nam_kor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [63]:
df.obs_datetime.describe()

name,type,count,unique,nulls,top,freq,min,median,max
obs_datetime,String,2965,43,0,2025-03-16 14:00:00,71,2025-03-16 13:30:00,2025-03-17 00:30:00,2025-03-17 10:30:00

In [66]:
val currentTime = df.obs_datetime.max()

df.filter { obs_datetime.equals(currentTime) }

sta_cde,sta_nam_kor,obs_dat,obs_tim,repair_gbn,obs_lay,wtr_tmp,dox,sal,obs_datetime,sta_cde1,gru_nam,lon,lat
bgj8a,기장,2025-03-17,10:30:00,1,1,11.7,null,null,2025-03-17 10:30:00,bgj8a,동해,129.227000,35.187000
bgj8a,기장,2025-03-17,10:30:00,1,2,11.8,null,null,2025-03-17 10:30:00,bgj8a,동해,129.227000,35.187000
bgj8a,기장,2025-03-17,10:30:00,1,3,11.8,null,null,2025-03-17 10:30:00,bgj8a,동해,129.227000,35.187000
bgna3,강릉,2025-03-17,10:30:00,1,1,6.3,null,null,2025-03-17 10:30:00,bgna3,동해,128.949200,37.799000
bgna3,강릉,2025-03-17,10:30:00,1,2,6.3,null,null,2025-03-17 10:30:00,bgna3,동해,128.949200,37.799000
bgna3,강릉,2025-03-17,10:30:00,1,3,6.2,null,null,2025-03-17 10:30:00,bgna3,동해,128.949200,37.799000
br001,태안 고남,2025-03-17,10:30:00,1,1,5.8,null,null,2025-03-17 10:30:00,br001,서해,126.433300,36.415800
bsc87,삼척,2025-03-17,10:30:00,1,1,7.6,null,null,2025-03-17 10:30:00,bsc87,동해,129.312700,37.302300
bsc87,삼척,2025-03-17,10:30:00,1,2,7.5,null,null,2025-03-17 10:30:00,bsc87,동해,129.312700,37.302300
bsc87,삼척,2025-03-17,10:30:00,1,3,6.9,null,null,2025-03-17 10:30:00,bsc87,동해,129.312700,37.302300
byd8a,영덕,2025-03-17,10:30:00,1,1,10.9,null,null,2025-03-17 10:30:00,byd8a,동해,129.437000,36.573700
byd8a,영덕,2025-03-17,10:30:00,1,2,10.8,null,null,2025-03-17 10:30:00,byd8a,동해,129.437000,36.573700
byd8a,영덕,2025-03-17,10:30:00,1,3,10.8,null,null,2025-03-17 10:30:00,byd8a,동해,129.437000,36.573700
byy87,양양,2025-03-17,10:30:00,1,1,6.7,null,null,2025-03-17 10:30:00,byy87,동해,128.699800,38.080800
byy87,양양,2025-03-17,10:30:00,1,2,6.3,null,null,2025-03-17 10:30:00,byy87,동해,128.699800,38.080800
byy87,양양,2025-03-17,10:30:00,1,3,6,null,null,2025-03-17 10:30:00,byy87,동해,128.699800,38.080800
egsi4,군산 신시도,2025-03-17,10:30:00,1,1,6.2,null,null,2025-03-17 10:30:00,egsi4,서해,126.442200,35.816800
ejhfc,장흥 회진,2025-03-17,10:30:00,1,1,8.7,10.6,null,2025-03-17 10:30:00,ejhfc,남해,126.980900,34.469900
ejhfc,장흥 회진,2025-03-17,10:30:00,1,2,8.7,null,null,2025-03-17 10:30:00,ejhfc,남해,126.980900,34.469900
ejj47,서제주,2025-03-17,10:30:00,1,1,11.9,null,34.8,2025-03-17 10:30:00,ejj47,남해,126.164000,33.310400

In [82]:
import kotlinx.datetime.LocalTime

val df_Current = df.filter {
    obs_datetime.equals(currentTime)   and repair_gbn.equals("1")
  //  gru_nam.equals("동해")
}.select{
    sta_nam_kor and obs_lay and wtr_tmp and gru_nam and    sta_cde  and  lon and lat and obs_datetime
}.convert { wtr_tmp }.with{ it.toFloat()
}.sortBy{sta_nam_kor  and obs_lay }

df_Current

sta_nam_kor,obs_lay,wtr_tmp,gru_nam,sta_cde,lon,lat,obs_datetime
강릉,1,6.300000,동해,bgna3,128.949200,37.799000,2025-03-17 10:30:00
강릉,2,6.300000,동해,bgna3,128.949200,37.799000,2025-03-17 10:30:00
강릉,3,6.200000,동해,bgna3,128.949200,37.799000,2025-03-17 10:30:00
거제 가배,1,9.100000,남해,fgg4c,128.566400,34.785100,2025-03-17 10:30:00
거제 일운,1,10.700000,남해,gi086,128.709400,34.803800,2025-03-17 10:30:00
고성 가진,1,5.500000,동해,fggo3,128.523900,38.368100,2025-03-17 10:30:00
고성 가진,2,5.200000,동해,fggo3,128.523900,38.368100,2025-03-17 10:30:00
고성 가진,3,5.100000,동해,fggo3,128.523900,38.368100,2025-03-17 10:30:00
고흥 소록도,1,8.500000,남해,fgsj3,127.122800,34.504900,2025-03-17 10:30:00
구룡포 하정,1,10.500000,동해,fghe8,129.549700,35.960700,2025-03-17 10:30:00
군산 신시도,1,6.200000,서해,egsi4,126.442200,35.816800,2025-03-17 10:30:00
기장,1,11.700000,동해,bgj8a,129.227000,35.187000,2025-03-17 10:30:00
기장,2,11.800000,동해,bgj8a,129.227000,35.187000,2025-03-17 10:30:00
기장,3,11.800000,동해,bgj8a,129.227000,35.187000,2025-03-17 10:30:00
남해 강진,1,8.300000,남해,eng5c,127.952200,34.874600,2025-03-17 10:30:00
남해 미조,1,8.800000,남해,fnm5b,128.049700,34.725500,2025-03-17 10:30:00
남해 미조,2,8.800000,남해,fnm5b,128.049700,34.725500,2025-03-17 10:30:00
목포,1,7.400000,서해,emp67,126.365300,34.789200,2025-03-17 10:30:00
백령도,1,4.900000,서해,fbn69,124.729500,37.950500,2025-03-17 10:30:00
삼척,1,7.600000,동해,bsc87,129.312700,37.302300,2025-03-17 10:30:00

In [83]:
df_Current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,69,42,0,강릉,3,null,null,강릉,완도 가교,해남 화산
obs_lay,String,69,3,0,1,42,null,null,1,1,3
wtr_tmp,Float,69,41,0,6.300000,4,8.156522,1.784202,4.900000,8.500000,11.900000
gru_nam,String,69,3,0,남해,35,null,null,남해,남해,서해
sta_cde,String,69,42,0,bgna3,3,null,null,bgj8a,fjh5a,wn087
lon,Double,69,42,0,128.949200,3,127.639399,1.190967,124.729500,127.708000,129.549700
lat,Double,69,42,0,37.799000,3,35.565158,1.387742,33.310400,34.808200,38.368100
obs_datetime,String,69,1,0,2025-03-17 10:30:00,69,null,null,2025-03-17 10:30:00,2025-03-17 10:30:00,2025-03-17 10:30:00

In [84]:
df_Current
    .filter { gru_nam.equals("동해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [96]:
df_Current
    .filter { gru_nam.equals("남해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [97]:
df_Current
    .filter { gru_nam.equals("서해") }
    .plot{
        layout{
            title = "Sea Water Quality"
            size = 1000 to 400
        }
        bars{
            alpha = 0.5
            x("sta_nam_kor"){
                axis{
                    name = "관측지점"
                }
            }
            y("wtr_tmp"){
                scale = continuous(0.0..15.0)
                axis {
                    name = "온도 °C"
                }
            }
            fillColor("obs_lay"){
                scale = categorical(
                    listOf(Color.BLUE, Color.GREEN, Color.RED),
                    listOf( "3", "2", "1"),
                )
                legend{
                    name= "관측 수심"
                    breaksLabeled("1" to "표층", "2" to "중층", "3" to "저층")
                }
            }

        }
    }

In [85]:
fun<T> makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<T>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        val delimiter1 = if (index < coordinates.size - 1) "," else ""

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        val propertieIterator = properties.entries.iterator()

        while (propertieIterator.hasNext()) {
            val (key, values) = propertieIterator.next()
            val delimiter2 = if (propertieIterator.hasNext()) "," else ""

            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\"${delimiter2} \n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t}${delimiter1}\n"

    }

    return first_str + features_str + end_str
}

In [86]:
df_Current.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
sta_nam_kor,String,69,42,0,강릉,3,null,null,강릉,완도 가교,해남 화산
obs_lay,String,69,3,0,1,42,null,null,1,1,3
wtr_tmp,Float,69,41,0,6.300000,4,8.156522,1.784202,4.900000,8.500000,11.900000
gru_nam,String,69,3,0,남해,35,null,null,남해,남해,서해
sta_cde,String,69,42,0,bgna3,3,null,null,bgj8a,fjh5a,wn087
lon,Double,69,42,0,128.949200,3,127.639399,1.190967,124.729500,127.708000,129.549700
lat,Double,69,42,0,37.799000,3,35.565158,1.387742,33.310400,34.808200,38.368100
obs_datetime,String,69,1,0,2025-03-17 10:30:00,69,null,null,2025-03-17 10:30:00,2025-03-17 10:30:00,2025-03-17 10:30:00

In [81]:
val coordinates = df_Current.filter {
    obs_lay.equals("1")
}.select{
   sta_cde and sta_nam_kor and  lon and lat
}.sortBy{sta_cde and  sta_nam_kor  }

coordinates

sta_cde,sta_nam_kor,lon,lat
bgj8a,기장,129.227000,35.187000
bgna3,강릉,128.949200,37.799000
br001,태안 고남,126.433300,36.415800
bsc87,삼척,129.312700,37.302300
byd8a,영덕,129.437000,36.573700
byy87,양양,128.699800,38.080800
egsi4,군산 신시도,126.442200,35.816800
ejhfc,장흥 회진,126.980900,34.469900
ejj47,서제주,126.164000,33.310400
emp67,목포,126.365300,34.789200
eng5c,남해 강진,127.952200,34.874600
esafc,신안 압해,126.224800,34.848300
fbn69,백령도,124.729500,37.950500
fgg4c,거제 가배,128.566400,34.785100
fggo3,고성 가진,128.523900,38.368100
fghe8,구룡포 하정,129.549700,35.960700
fgsj3,고흥 소록도,127.122800,34.504900
fhhfc,해남 화산,126.421600,34.423500
fjdfc,진도 전두,126.218900,34.537600
fjh5a,해남 임하,126.267200,34.606900

In [ ]:
val points = df_Current.filter {
    obs_lay.equals("1")
}.select{
    sta_cde and sta_nam_kor and  lon and lat
}.sortBy{sta_cde and  sta_nam_kor
}.map { Pair(lon, lat) }.toList()

In [ ]:
val properties = df_Current.filter {
   obs_lay.equals("1")
}
    .add("tempBoundary"){
        when(wtr_tmp.toFloat()) {
            in 0.0..4.9 -> "Low"
            in 5.0..7.9 -> "Middle"
            in 8.0..15.9 -> "High"
            else -> "Unknown"
        }
    }
    .select {sta_cde and  sta_nam_kor and wtr_tmp and obs_datetime  and "tempBoundary"}
    .sortBy{sta_cde and  sta_nam_kor  }.toMap()

In [104]:
DataFrame.readJsonStr(makePointGeoJSON(points, properties))
    .writeJson("/Volumes/WorkSpace/Notebook/data/nifsPoint.json")

In [105]:
val southKorea = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/southkorea.geojson")
val staPoint = GeoDataFrame.readGeoJson("/Volumes/WorkSpace/Notebook/data/nifsPoint.json")

In [106]:
val southKoreaBounds: Envelope = southKorea.bounds().also {
    // Use JTS API for in-place envelope expansion
    it.expandBy(0.2)
}

In [107]:

southKorea.plot{
    layout{
        title = "Korea Sea Water Quality"
        size = 1400 to 1400
        //  theme = Theme.HIGH_CONTRAST_DARK
        style(Style.BW) {
            this.panel.background {
                fillColor =  Color.hex("#537ab5")
                borderLineColor = Color.hex("#EFC623")
                borderLineWidth = 6.0
            }
        }
    }

    geoMap{
        fillColor= Color.hex("#e5f5e0")
        borderLine {
            width = 0.5
            color = Color.hex("#a1d99b")
        }
    }

    withData(staPoint) {

        geoPoints {
            size = 5.0
            symbol = Symbol.CIRCLE_FILLED
            fillColor(tempBoundary)
            tooltips(title = value(sta_nam_kor)){
                line("수온 ${value(wtr_tmp)}°C")
                line("측정시간", value(obs_datetime))
            }
        }
    }


}