In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [5]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250225"
val EDATE = "20250225"
val numOfRows = "100"
val maxPage = 100

In [6]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [7]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250225&EDATE=20250225&numOfRows=100

In [8]:
val rawDf = load(url, maxPage)
rawDf

Can not get nested column 'item' from ValueColumn 'items'

In [9]:
val rawDfConcat = rawDf.item.concat()

In [10]:
val rawDfParse = rawDfConcat.parse()

In [11]:
rawDfParse

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2
덕천,34.350000,2025-02-25T10:00,bdch3,100000,11.200000,동해,null,null
구룡포 하정,null,2025-02-25T10:00,fghe8,100000,10,동해,null,null
고성 가진,null,2025-02-25T10:00,fggo3,100000,5.400000,동해,5.200000,5.300000
온양,34.326000,2025-02-25T10:00,byyh3,100000,10.100000,동해,null,null
양양,null,2025-02-25T10:00,byy87,100000,5.300000,동해,5.300000,5.300000
영덕,null,2025-02-25T10:00,byd8a,100000,10.200000,동해,10.100000,10.100000
삼척,null,2025-02-25T10:00,bsc87,100000,9.100000,동해,8.900000,9
나곡,34.307000,2025-02-25T10:00,bngh3,100000,10.900000,동해,null,null
진하,34.299000,2025-02-25T10:00,bjhh3,100000,11.800000,동해,null,null
고리,35.214000,2025-02-25T10:00,bgrh3,100000,12.500000,동해,null,null
강릉,null,2025-02-25T10:00,bgna3,100000,6.500000,동해,6.200000,6.400000
기장(한수원),34.496000,2025-02-25T10:00,bgjh3,100000,12.400000,동해,null,null
기장,null,2025-02-25T10:00,bgj8a,100000,12,동해,12,12
덕천,34.350000,2025-02-25T09:30,bdch3,093000,11.600000,동해,null,null
구룡포 하정,null,2025-02-25T09:30,fghe8,093000,10,동해,null,null
고성 가진,null,2025-02-25T09:30,fggo3,093000,5.400000,동해,5.200000,5.300000
온양,34.327000,2025-02-25T09:30,byyh3,093000,10.100000,동해,null,null
양양,null,2025-02-25T09:30,byy87,093000,5.300000,동해,5.300000,5.300000
영덕,null,2025-02-25T09:30,byd8a,093000,10.200000,동해,10.100000,10.100000
삼척,null,2025-02-25T09:30,bsc87,093000,9,동해,8.900000,8.900000

In [12]:
rawDfParse.staCde.distinct()

staCde
bdch3
fghe8
fggo3
byyh3
byy87
byd8a
bsc87
bngh3
bjhh3
bgrh3
bgna3
bgjh3
bgj8a

In [13]:
rawDfParse.plot{
    x(obsDtm) { axis.name = "관측일시"}
    y(wtrTmp_1) {axis.name ="표층수온"}
    y.axis.limits = 0.0..15.0
    line{
        color(staNamKor){
            scale = continuous(Color.GREEN..Color.RED)
            legend{
                name = "관측소명"
            }
        }
    }

    layout {
        title = "관측지점별 해수 정보"
        size = 1200 to 500
    }
}

In [14]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE_NEW2.csv")
staCodeDf

staCde,gruNam,name,longitude,latitude
fgmk6,남해,강진 마량,126.813286,34.444798
fgsl6,남해,강진 사초,126.769100,34.459900
ms002,남해,거제,128.458900,34.535900
fgg4c,남해,거제 가배,128.566400,34.785100
fggj7,남해,거제 가조,128.514200,34.977200
gi086,남해,거제 일운,128.709400,34.803800
btei5,남해,거제 해금강,128.690833,34.735833
bgyga,남해,고성 용정,128.500860,34.989700
bgjgb,남해,고성 장좌,128.465450,34.970800
ys002,남해,고흥,127.350900,34.261200
fggm6,남해,고흥 금산,127.097000,34.452600
fgnm6,남해,고흥 남열,127.465600,34.571300
fgdl4,남해,고흥 동촌,127.225800,34.433000
fgpo4,남해,고흥 발포,127.370100,34.441600
bgui5,남해,고흥 부아도,127.178611,34.375278
fgbo4,남해,고흥 비사도,127.455700,34.557900
fgsj3,남해,고흥 소록도,127.122800,34.504900
fgso4,남해,고흥 시산,127.277600,34.384700
fgsl4,남해,고흥 신촌,127.101700,34.473800
fgyl4,남해,고흥 연소,127.118100,34.436500

In [39]:
val df = rawDfParse.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.obsDtm into "datetime"
    currentData.gruNam into "gruNam"
    currentData.staNamKor into "name"
    currentData.wtrTmp_1 into "currentTemp"
}.join(staCodeDf.select{  gruNam and  name and staCde and latitude and longitude}){
     "gruNam" and "name" and "staCde"
}

df

staCde,datetime,gruNam,name,currentTemp,latitude,longitude
bdch3,2025-02-25T10:00,동해,덕천,11.200000,37.100000,129.404100
fghe8,2025-02-25T10:00,동해,구룡포 하정,10,35.960700,129.549700
fggo3,2025-02-25T10:00,동해,고성 가진,5.400000,38.368100,128.523900
byyh3,2025-02-25T10:00,동해,온양,10.100000,37.019400,129.425000
byy87,2025-02-25T10:00,동해,양양,5.300000,38.080800,128.699800
byd8a,2025-02-25T10:00,동해,영덕,10.200000,36.573700,129.437000
bsc87,2025-02-25T10:00,동해,삼척,9.100000,37.302300,129.312700
bngh3,2025-02-25T10:00,동해,나곡,10.900000,37.119100,129.395800
bjhh3,2025-02-25T10:00,동해,진하,11.800000,35.384700,129.368000
bgrh3,2025-02-25T10:00,동해,고리,12.500000,35.318600,129.314700
bgna3,2025-02-25T10:00,동해,강릉,6.500000,37.799000,128.949200
bgjh3,2025-02-25T10:00,동해,기장(한수원),12.400000,35.182500,129.235200
bgj8a,2025-02-25T10:00,동해,기장,12,35.187000,129.227000

In [59]:
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staCde,String,13,13,0,bdch3,1,null,null,bdch3,bngh3,fghe8
datetime,kotlinx.datetime.LocalDateTime,13,1,0,2025-02-25T10:00,13,null,null,2025-02-25T10:00,2025-02-25T10:00,2025-02-25T10:00
gruNam,String,13,1,0,동해,13,null,null,동해,동해,동해
name,String,13,13,0,덕천,1,null,null,강릉,나곡,진하
currentTemp,Number,13,13,0,11.200000,1,9.800000,2.538700,5.300000,10.200000,12.500000
latitude,Double,13,13,0,37.100000,1,36.645838,1.134755,35.182500,37.019400,38.368100
longitude,Double,13,13,0,129.404100,1,129.218623,0.306979,128.523900,129.314700,129.549700

In [92]:
val dfBoundary = df.add("tempBoundary"){
    when(currentTemp.toDouble()) {
        in 0.0..4.9 -> "Low"
        in 5.0..7.9 -> "Middle"
        in 8.0..15.9 -> "High"
        else -> "Unknown"
    }
}
dfBoundary

staCde,datetime,gruNam,name,currentTemp,latitude,longitude,tempBoundary
bdch3,2025-02-25T10:00,동해,덕천,11.200000,37.100000,129.404100,High
fghe8,2025-02-25T10:00,동해,구룡포 하정,10,35.960700,129.549700,High
fggo3,2025-02-25T10:00,동해,고성 가진,5.400000,38.368100,128.523900,Middle
byyh3,2025-02-25T10:00,동해,온양,10.100000,37.019400,129.425000,High
byy87,2025-02-25T10:00,동해,양양,5.300000,38.080800,128.699800,Middle
byd8a,2025-02-25T10:00,동해,영덕,10.200000,36.573700,129.437000,High
bsc87,2025-02-25T10:00,동해,삼척,9.100000,37.302300,129.312700,High
bngh3,2025-02-25T10:00,동해,나곡,10.900000,37.119100,129.395800,High
bjhh3,2025-02-25T10:00,동해,진하,11.800000,35.384700,129.368000,High
bgrh3,2025-02-25T10:00,동해,고리,12.500000,35.318600,129.314700,High
bgna3,2025-02-25T10:00,동해,강릉,6.500000,37.799000,128.949200,Middle
bgjh3,2025-02-25T10:00,동해,기장(한수원),12.400000,35.182500,129.235200,High
bgj8a,2025-02-25T10:00,동해,기장,12,35.187000,129.227000,High

In [93]:
dfBoundary.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staCde,String,13,13,0,bdch3,1,null,null,bdch3,bngh3,fghe8
datetime,kotlinx.datetime.LocalDateTime,13,1,0,2025-02-25T10:00,13,null,null,2025-02-25T10:00,2025-02-25T10:00,2025-02-25T10:00
gruNam,String,13,1,0,동해,13,null,null,동해,동해,동해
name,String,13,13,0,덕천,1,null,null,강릉,나곡,진하
currentTemp,Number,13,13,0,11.200000,1,9.800000,2.538700,5.300000,10.200000,12.500000
latitude,Double,13,13,0,37.100000,1,36.645838,1.134755,35.182500,37.019400,38.368100
longitude,Double,13,13,0,129.404100,1,129.218623,0.306979,128.523900,129.314700,129.549700
tempBoundary,String,13,2,0,High,10,null,null,High,High,Middle

In [73]:
%useLatestDescriptors
%use lets-plot
%use lets-plot-gt

In [28]:
import org.geotools.geojson.feature.FeatureJSON
val southKr = FeatureJSON().readFeatureCollection(File("/Users/unchil/Downloads/kr.json").readText())
val mapBound = southKr.bounds
mapBound.expandBy(0.2)

In [94]:
fun<T> makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<T>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        properties.forEach { key, values ->
            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\",\n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t},\n"

    }

    return first_str + features_str + end_str
}

makePointGeoJSON(
    dfBoundary.select{longitude and latitude}.map{ Pair(longitude, latitude) }.toList(),
    dfBoundary.select{name and currentTemp and datetime and staCde and tempBoundary }.toMap()
)

{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.4041, 37.1]
			},
			"properties": {
				"name": "덕천",
				"currentTemp": "11.2",
				"datetime": "2025-02-25T10:00",
				"staCde": "bdch3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.5497, 35.9607]
			},
			"properties": {
				"name": "구룡포 하정",
				"currentTemp": "10",
				"datetime": "2025-02-25T10:00",
				"staCde": "fghe8",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.5239, 38.3681]
			},
			"properties": {
				"name": "고성 가진",
				"currentTemp": "5.4",
				"datetime": "2025-02-25T10:00",
				"staCde": "fggo3",
				"tempBoundary": "Middle",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.425, 37.0194]
			},
			"properties": {
				"name": "온양",
				"currentTemp": "10.1",
				"datetime": "2025-02-25T10:00",
				"staCde": "byyh3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.6998, 38.0808]
			},
			"properties": {
				"name": "양양",
				"currentTemp": "5.3",
				"datetime": "2025-02-25T10:00",
				"staCde": "byy87",
				"tempBoundary": "Middle",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.437, 36.5737]
			},
			"properties": {
				"name": "영덕",
				"currentTemp": "10.2",
				"datetime": "2025-02-25T10:00",
				"staCde": "byd8a",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3127, 37.3023]
			},
			"properties": {
				"name": "삼척",
				"currentTemp": "9.1",
				"datetime": "2025-02-25T10:00",
				"staCde": "bsc87",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3958, 37.1191]
			},
			"properties": {
				"name": "나곡",
				"currentTemp": "10.9",
				"datetime": "2025-02-25T10:00",
				"staCde": "bngh3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.368, 35.3847]
			},
			"properties": {
				"name": "진하",
				"currentTemp": "11.8",
				"datetime": "2025-02-25T10:00",
				"staCde": "bjhh3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3147, 35.3186]
			},
			"properties": {
				"name": "고리",
				"currentTemp": "12.5",
				"datetime": "2025-02-25T10:00",
				"staCde": "bgrh3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.9492, 37.799]
			},
			"properties": {
				"name": "강릉",
				"currentTemp": "6.5",
				"datetime": "2025-02-25T10:00",
				"staCde": "bgna3",
				"tempBoundary": "Middle",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.2352, 35.1825]
			},
			"properties": {
				"name": "기장(한수원)",
				"currentTemp": "12.4",
				"datetime": "2025-02-25T10:00",
				"staCde": "bgjh3",
				"tempBoundary": "High",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.227, 35.187]
			},
			"properties": {
				"name": "기장",
				"currentTemp": "12",
				"datetime": "2025-02-25T10:00",
				"staCde": "bgj8a",
				"tempBoundary": "High",
			}
		},
	]
}

In [95]:
val point = FeatureJSON().readFeatureCollection(
    makePointGeoJSON(
        dfBoundary.select{longitude and latitude}.map{Pair(longitude, latitude) }.toList(),
        dfBoundary.select{name and currentTemp and datetime and staCde and tempBoundary}.toMap()
    )
)

In [96]:
letsPlot() +
        geomMap(map = southKr.toSpatialDataset() , color = "#a1d99b", fill = "#e5f5e0" ) +
        geomRect(xmin= mapBound.minX, xmax =mapBound.maxX, ymax=mapBound.maxY, ymin= mapBound.minY, alpha = 0, fill = "black", color="#EFC623", size=6) +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        geomPoint(
            map= point.toSpatialDataset() ,
            showLegend=true,
            size=3,
            shape = 21,
            fillBy = "paint_a",
            tooltips = layerTooltips().title("@name[@staCde]").line("수온:@currentTemp°C\n@datetime")
        ){
            paint_a = "tempBoundary"
        } +
        geomText(map=point.toSpatialDataset() ,   position = positionNudge(x = +.2) , color="yellow"){ label =  "currentTemp"} +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = -.2) , color="black"){ label = "name" } +
        theme(panelBackground = elementRect(color = "black", fill = "#537ab5")) +
        ggtitle("Korea EastSea Water Quality") +
        ggsize( width = 1000, height = 1000)