In [2]:
%useLatestDescriptors
%use dataframe
%use kandy

In [13]:
USE{
    dependencies("org.json:json:20250107")
}

In [14]:
import org.json.XML

In [15]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [16]:
val serviceKeyFilePath = "/Volumes/WorkSpace/Notebook/data/OceanMensurationService.json"
val SDATE = "20250228"
val EDATE = "20250228"
val numOfRows = "100"
val maxPage = 500

In [17]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [18]:
val serviceInfo = DataRow.readJson(path=serviceKeyFilePath)

In [19]:
val url_East = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [9]:
val url_West = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.WEST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [10]:
val url_South = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.SOUTH.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [20]:
val rawEastDf = load(url_East,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [22]:
val rawEastConcat = rawEastDf.item.concat()

In [23]:
rawEastConcat.head()

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2
덕천,34.280000,2025-02-28 23:30:00,bdch3,233000,10.200000,동해,null,null
구룡포 하정,null,2025-02-28 23:30:00,fghe8,233000,10.900000,동해,null,null
고성 가진,null,2025-02-28 23:30:00,fggo3,233000,5.400000,동해,4.500000,5.300000
온양,34.333000,2025-02-28 23:30:00,byyh3,233000,9.800000,동해,null,null
영덕,null,2025-02-28 23:30:00,byd8a,233000,10.400000,동해,10,10.100000

In [30]:
rawEastConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,522,12,0,기장,53,null,null,강릉,기장(한수원),진하
cdt_1,Double?,522,150,287,34.328000,5,34.466013,0.312847,34.147000,34.333000,35.184000
obsDtm,String,522,48,0,2025-02-28 23:30:00,12,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,522,12,0,bgj8a,53,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,522,48,0,233000,12,null,null,null,null,null
wtrTmp_1,Number,522,54,0,11.700000,52,10.177203,1.845854,5.400000,10.400000,13.400000
gruNam,String,522,1,0,동해,522,null,null,동해,동해,동해
wtrTmp_3,Number?,522,42,278,10,46,8.277869,2.545439,4.500000,8.800000,11.800000
wtrTmp_2,Number?,522,40,278,10,43,8.703279,2.253573,5.100000,9.150000,11.800000

In [33]:
val rawEastParse = rawEastConcat.parse()

In [65]:
rawEastParse
    .select{ staNamKor and wtrTmp_1 }
    .convert( "wtrTmp_1" ).toFloat()
    .sortBy { staNamKor }
    .groupBy{staNamKor}
    .plot{

        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1400 to 600
            theme = Theme.HIGH_CONTRAST_DARK
            style(Style.Minimal2)
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("staNamKor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }

            x.axis.name = "관측 지점"
            y.axis.name = "수온 °C"
            y.axis.limits = 3.0..15.0
        }

    }

In [12]:
val rawWestDf = load(url_West,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [16]:
val rawWestConcat = rawWestDf.item.concat()

In [17]:
rawWestConcat.head()

staNamKor,cdt_1,obsDtm,staCde,dox_1,obsTim,wtrTmp_1,gruNam,dox_2,wtrTmp_2
태안 고남,31.200000,2025-02-27 23:30:00,br001,11.700000,233000,4,서해,null,null
서산 지곡,null,2025-02-27 23:30:00,sj086,null,233000,4.200000,서해,null,null
태안 파도리,null,2025-02-27 23:30:00,ftpk5,null,233000,4.700000,서해,14.100000,4.600000
태안 대야도,null,2025-02-27 23:30:00,ftdk5,12.500000,233000,4.100000,서해,null,4.100000
서산 창리,31.600000,2025-02-27 23:30:00,fsch6,13,233000,3.600000,서해,null,3.300000

In [13]:
val rawSouthDf = load(url_South,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [18]:
val rawSouthConcat = rawSouthDf.item.concat()

In [19]:
rawSouthConcat.head()

staNamKor,obsDtm,staCde,dox_1,obsTim,wtrTmp_1,gruNam,wtrTmp_2,cdt_1,wtrTmp_3,dox_3,dox_2
장흥 회진,2025-02-27 23:30:00,ejhfc,12.200000,233000,7.300000,남해,7.300000,null,null,null,null
완도 노화도,2025-02-27 23:30:00,wn087,null,233000,6.700000,남해,null,null,null,null,null
완도 금일,2025-02-27 23:30:00,wk094,null,233000,7.600000,남해,null,null,null,null,null
완도 청산,2025-02-27 23:30:00,wc001,10.100000,233000,8.400000,남해,null,null,null,null,null
통영 사량,2025-02-27 23:30:00,ty005,10.800000,233000,7.100000,남해,null,null,null,null,null

In [20]:
val rawDf = listOf(rawEastConcat, rawWestConcat, rawSouthConcat).concat()

In [21]:
rawDf.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,4377,143,0,남해 강진,72,null,null,강릉,여수 신월,해남 황산
cdt_1,Number?,4377,156,3849,34.800000,52,33.670780,1.270628,30.700000,34.297000,35.257000
obsDtm,String,4377,48,0,2025-02-27 18:00:00,141,null,null,2025-02-27 00:00:00,2025-02-27 12:00:00,2025-02-27 23:30:00
staCde,String,4377,143,0,eng5c,72,null,null,bdch3,fhyk7,wn087
obsTim,Comparable<*>?,4377,49,2060,000000,56,null,null,null,null,null
wtrTmp_1,Comparable<*>?,4377,109,8,6.200000,147,null,null,null,null,null
gruNam,String,4377,3,0,남해,2887,null,null,남해,남해,서해
wtrTmp_3,Number?,4377,43,3987,9.200000,33,8.027436,2.152572,4.600000,8.050000,11.900000
wtrTmp_2,Number?,4377,70,3379,9.200000,53,7.045391,2.030518,3.200000,6.900000,11.900000
dox_1,Number?,4377,55,3472,10.200000,79,11.368508,1.444341,8.900000,11.300000,14.500000
dox_2,Number?,4377,28,4240,10.700000,16,12.294161,1.103122,10.500000,12.100000,14.200000
dox_3,Number?,4377,18,4281,12.900000,14,11.779167,0.891588,10.500000,11.700000,13.300000

In [22]:
val rawDfParse = rawDf.parse()

In [197]:
rawDfParse.filter{gruNam.equals("동해")}
    .drop{ staNamKor in dropList }
    .select{ staNamKor and wtrTmp_1 }
    .convert( "wtrTmp_1" ).toFloat()
    .sortBy { staNamKor }
    .plot{

        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1400 to 600
        //    theme = Theme.HIGH_CONTRAST_DARK
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
            }
        }
    }

In [198]:
rawDfParse.filter{gruNam.equals("서해")}
    .drop{ staNamKor in dropList }
    .select{ staNamKor and wtrTmp_1 }
    .convert( "wtrTmp_1" ).toFloat()
    .sortBy { staNamKor }
    .plot{

        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1400 to 600
  //          theme = Theme.HIGH_CONTRAST_DARK
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
            }
        }
    }

In [199]:
rawDfParse.filter{gruNam.equals("남해")}
    .drop{ staNamKor in dropList }
    .select{ staNamKor and wtrTmp_1 }
    .convert( "wtrTmp_1" ).toFloat()
    .sortBy { staNamKor }
    .plot{

        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1400 to 600
   //         theme = Theme.HIGH_CONTRAST_DARK
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
            }
        }
    }

In [56]:
val dropList = rawDfParse.filter {wtrTmp_1 == null }.distinct { staNamKor }.staNamKor.toList()
dropList

[함평 석두, 신안 압해, 완도 동촌, 완도 덕동]

In [66]:
rawDfParse.drop{ staNamKor in dropList }.filter{gruNam.equals("동해")}.convert( "wtrTmp_1" ).toFloat()
    .plot{

        layout {
            title = "관측지점별 해수 정보"
            size = 1400 to 600
        }

        x(obsDtm) { axis.name = "관측일시"}
        y(wtrTmp_1) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(staNamKor){
             //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

      //  facetWrap(nRow = 3){ facet(gruNam)   }

}

In [67]:
rawDfParse.drop{ staNamKor in dropList }.filter{gruNam.equals("서해")}.convert( "wtrTmp_1" ).toFloat()
    .plot{

        layout {
            title = "관측지점별 해수 정보"
            size = 1400 to 600
        }

        x(obsDtm) { axis.name = "관측일시"}
        y(wtrTmp_1) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(staNamKor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [68]:
rawDfParse.drop{ staNamKor in dropList }.filter{gruNam.equals("남해")}.convert( "wtrTmp_1" ).toFloat()
    .plot{

        layout {
            title = "관측지점별 해수 정보"
            size = 1400 to 600
        }

        x(obsDtm) { axis.name = "관측일시"}
        y(wtrTmp_1) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(staNamKor){
                //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

        //  facetWrap(nRow = 3){ facet(gruNam)   }

    }

In [105]:
val url_East_Month = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=20250221&EDATE=20250227&numOfRows=100"

In [106]:
val rawEastMonthDf = load(url_East_Month, 200 )

Can not get nested column 'item' from ValueColumn 'items'

In [107]:
val rawEastMonthConcat = rawEastMonthDf.item.concat()

In [108]:
rawEastMonthConcat.writeJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [3]:
val rawEastMonthConcat = DataFrame.readJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [9]:
val rawEastMonthParse = rawEastMonthConcat.parse()

In [5]:
rawEastMonthParse.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000

In [10]:
val rawEastMonthParse2 = rawEastMonthParse.convert( "wtrTmp_1" ).toDouble()
    .add{
        "측정일" from obsDtm.map { it.dayOfMonth }
    }

rawEastMonthParse2.head()

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2,측정일
덕천,34.298000,2025-02-27T23:30,bdch3,233000,11.100000,동해,null,null,27
구룡포 하정,null,2025-02-27T23:30,fghe8,233000,10.400000,동해,null,null,27
고성 가진,null,2025-02-27T23:30,fggo3,233000,5.400000,동해,4.900000,5.300000,27
온양,34.359000,2025-02-27T23:30,byyh3,233000,10.000000,동해,null,null,27
영덕,null,2025-02-27T23:30,byd8a,233000,10.400000,동해,10.000000,10.200000,27

In [11]:
rawEastMonthParse2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000
측정일,Int,3955,7,0,23,576,23.971176,1.986214,21,24,27

In [12]:
rawEastMonthParse2.groupBy { staNamKor and "측정일" }
    .aggregate {
        min{wtrTmp_1} into "min"
        max{wtrTmp_1} into "max"
        mean{wtrTmp_1} into "mean"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 800 to 400
        }

        ribbon {

            x("측정일") {
                axis.name = "측정일"
            }

            y.axis {
                limits = 2.0..15.0
                name = "수온 최저~최고"
            }

            yMin("min")
            yMax("max")
            fillColor("staNamKor"){
                legend {
                    name = "관측지점"
                }
            }
            alpha = 0.6
            borderLine.width = 0.0

            tooltips(title = value(staNamKor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                //line(day, format = "d")
                varLine("측정일", "{d}")
            }
        }


    }