In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [5]:
val serviceKeyFilePath = "/Volumes/WorkSpace/Notebook/data/OceanMensurationService.json"
val SDATE = "20250312"
val EDATE = "20250312"
val numOfRows = "100"
val maxPage = 500

In [6]:
fun load(path:String, maxPage:Int): AnyFrame {


    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [7]:
val serviceInfo = DataRow.readJson(path=serviceKeyFilePath)

In [8]:
val url_East = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [9]:
val url_West = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.WEST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [10]:
val url_South = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.SOUTH.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [11]:
fun measureTimeMillis(block: () -> Unit): String {
    val startTime = System.currentTimeMillis()
    block()
    val endTime = System.currentTimeMillis()
    val time = endTime - startTime
    return "Time:${time}ms (${time/(60*1000)}m ${(time%(60*1000))/1000}s ${((time%(60*1000))%1000)}ms)"
}

In [15]:
measureTimeMillis{
 load(url_South,maxPage)
}

Can not get nested column 'item' from ValueColumn 'items'

Time:342817ms (5m 42s 817ms)

In [9]:
val rawEastDf = load(url_East,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [10]:
rawEastDf

In [11]:
val rawEastConcat = rawEastDf.item.concat()

In [12]:
rawEastConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,564,13,0,기장,52,null,null,강릉,나곡,진하
cdt_1,Double?,564,194,330,34.295000,4,34.305893,0.455302,33.181000,34.266000,35.248000
obsDtm,String,564,48,0,2025-03-12 23:30:00,13,null,null,2025-03-12 00:00:00,2025-03-12 11:30:00,2025-03-12 23:30:00
staCde,String,564,13,0,bgj8a,52,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,564,48,0,233000,13,null,null,null,null,null
wtrTmp_1,Number?,564,78,16,11.800000,76,9.767701,2.069699,5.200000,10.250000,13.700000
gruNam,String,564,1,0,동해,564,null,null,동해,동해,동해
wtrTmp_3,Number?,564,60,294,11.800000,28,7.102963,2.893511,3.200000,6.000000,11.900000
wtrTmp_2,Number?,564,60,294,11.900000,29,7.982963,2.480977,3.900000,7.300000,11.900000

In [13]:
rawEastConcat.groupBy{ staNamKor and staCde}.count()

staNamKor,staCde,count
덕천,bdch3,38
구룡포 하정,fghe8,44
고성 가진,fggo3,44
온양,byyh3,36
양양,byy87,44
영덕,byd8a,47
삼척,bsc87,48
나곡,bngh3,42
진하,bjhh3,39
고리,bgrh3,39
강릉,bgna3,51
기장(한수원),bgjh3,40
기장,bgj8a,52

In [14]:
val rawWestDf = load(url_West,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [ ]:
rawWestDf

In [15]:
val rawWestConcat = rawWestDf.item.concat()

In [16]:
rawWestConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,961,30,0,군산 신시도,57,null,null,군산 신시도,신안 송공,해남 임하
cdt_1,Number?,961,9,866,31,31,31.312632,0.299731,30.900000,31.200000,31.700000
obsDtm,String,961,48,0,2025-02-28 20:00:00,30,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,961,30,0,egsi4,57,null,null,br001,fjoo4,sj086
dox_1,Number?,961,31,720,9,37,11.761411,1.632395,8.900000,12.200000,13.800000
obsTim,Comparable<*>?,961,49,428,210000,13,null,null,null,null,null
wtrTmp_1,Number,961,60,0,4.100000,60,5.436629,1.281060,3.500000,5.400000,13.100000
gruNam,String,961,1,0,서해,961,null,null,서해,서해,서해
dox_2,Number?,961,11,920,13.100000,17,13.426829,0.356388,13.100000,13.200000,14.000000
wtrTmp_2,Number?,961,22,782,6.100000,18,4.587709,0.997167,3.500000,4.100000,6.400000

In [17]:
val rawSouthDf = load(url_South,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [ ]:
rawSouthConcat

In [18]:
val rawSouthConcat = rawSouthDf.item.concat()

In [19]:
rawSouthConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,2882,101,0,서제주,74,null,null,강진 마량,완도 노화도,해남 황산
obsDtm,String,2882,48,0,2025-02-28 18:00:00,99,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,2882,101,0,ejj47,74,null,null,ejhfc,fjil6,wn087
dox_1,Number?,2882,46,2219,10.100000,71,11.138311,1.307500,9.000000,11.000000,13.700000
obsTim,Comparable<*>?,2882,49,1637,000000,35,null,null,null,null,null
wtrTmp_1,Number,2882,72,0,7.600000,180,7.354997,1.571385,4.700000,7.200000,14.100000
gruNam,String,2882,1,0,남해,2882,null,null,남해,남해,남해
wtrTmp_2,Number?,2882,39,2341,7.600000,48,7.492421,1.060939,5.200000,7.600000,9.300000
cdt_1,Double?,2882,7,2688,34.800000,73,33.782990,0.853259,32.800000,33.600000,34.900000
wtrTmp_3,Double?,2882,12,2773,9.200000,36,7.908257,1.330422,6.400000,7.800000,9.300000
dox_3,Number?,2882,9,2827,10.600000,13,11.714545,0.819308,10.600000,11.700000,13.000000
dox_2,Number?,2882,14,2827,11.800000,10,11.710909,0.821172,10.500000,11.700000,13.100000

In [14]:
//val rawDf = listOf(rawEastConcat, rawWestConcat, rawSouthConcat).concat()
val rawDf = listOf(rawEastConcat).concat()

In [15]:
val rawDfParse = rawDf.parse()

In [19]:
rawDfParse.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,523,12,0,강릉,51,null,null,강릉,기장(한수원),진하
cdt_1,Double?,523,151,282,34.194000,9,34.370560,0.312160,33.761000,34.228000,35.087000
obsDtm,kotlinx.datetime.LocalDateTime,523,48,0,2025-03-03T23:30,12,null,null,2025-03-03T00:00,2025-03-03T12:00,2025-03-03T23:30
staCde,String,523,12,0,bgna3,51,null,null,bdch3,bjhh3,fghe8
obsTim,Comparable<*>,523,48,0,233000,12,null,null,null,null,null
wtrTmp_1,Number,523,40,0,9.100000,73,9.975908,1.841006,4.900000,10.200000,13.200000
gruNam,String,523,1,0,동해,523,null,null,동해,동해,동해
wtrTmp_3,Number?,523,59,286,11.600000,31,8.551477,2.620561,2.700000,9.100000,11.800000
wtrTmp_2,Number?,523,31,286,9.100000,43,8.959916,2.263574,4.800000,9.100000,11.800000

In [16]:
val rawDfParse2 = rawDfParse.convert( "wtrTmp_1" ).toDouble()
    .add{
        "hour" from obsDtm.map { it.hour }
    }.select{
        "staNamKor" and "wtrTmp_1" and "obsDtm" and "hour" and "gruNam" and "staCde"
    }
rawDfParse2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,564,13,0,기장,52,null,null,강릉,나곡,진하
wtrTmp_1,Double?,564,78,16,11.800000,76,9.767701,2.069699,5.200000,10.250000,13.700000
obsDtm,kotlinx.datetime.LocalDateTime,564,48,0,2025-03-12T23:30,13,null,null,2025-03-12T00:00,2025-03-12T11:30,2025-03-12T23:30
hour,Int,564,24,0,20,26,11.460993,6.920013,0,11,23
gruNam,String,564,1,0,동해,564,null,null,동해,동해,동해
staCde,String,564,13,0,bgj8a,52,null,null,bdch3,bngh3,fghe8

In [17]:
// Time series data at 30-minute intervals for one day
rawDfParse2.groupBy{gruNam and staNamKor and staCde}.count()

gruNam,staNamKor,staCde,count
동해,덕천,bdch3,38
동해,구룡포 하정,fghe8,44
동해,고성 가진,fggo3,44
동해,온양,byyh3,36
동해,양양,byy87,44
동해,영덕,byd8a,47
동해,삼척,bsc87,48
동해,나곡,bngh3,42
동해,진하,bjhh3,39
동해,고리,bgrh3,39
동해,강릉,bgna3,51
동해,기장(한수원),bgjh3,40
동해,기장,bgj8a,52

In [ ]:
val timeZone = TimeZone.of("UTC+0")
val startDate = LocalDateTime(2025, 2, 28, 0, 0)
val endDate = LocalDateTime(2025, 2, 28, 23, 31)
val intervalMinute = 30

val date = generateSequence(startDate.toInstant(timeZone)){
        it.plus(intervalMinute, DateTimeUnit.MINUTE, timeZone) }
    .takeWhile { it  <= endDate.toInstant(timeZone) }
    .toList()

val dateDf = dataFrameOf("date" to date)
dateDf.describe()

In [21]:
rawDfParse2

staNamKor,wtrTmp_1,obsDtm,hour,gruNam,staCde
덕천,8.500000,2025-03-12T23:30,23,동해,bdch3
구룡포 하정,11.100000,2025-03-12T23:30,23,동해,fghe8
고성 가진,5.800000,2025-03-12T23:30,23,동해,fggo3
온양,10.200000,2025-03-12T23:30,23,동해,byyh3
양양,7.700000,2025-03-12T23:30,23,동해,byy87
영덕,10.600000,2025-03-12T23:30,23,동해,byd8a
삼척,8.300000,2025-03-12T23:30,23,동해,bsc87
나곡,8.200000,2025-03-12T23:30,23,동해,bngh3
진하,11.700000,2025-03-12T23:30,23,동해,bjhh3
고리,12.500000,2025-03-12T23:30,23,동해,bgrh3
강릉,9.600000,2025-03-12T23:30,23,동해,bgna3
기장(한수원),11.700000,2025-03-12T23:30,23,동해,bgjh3
기장,11.900000,2025-03-12T23:30,23,동해,bgj8a
덕천,8.200000,2025-03-12T23:00,23,동해,bdch3
구룡포 하정,11.100000,2025-03-12T23:00,23,동해,fghe8
고성 가진,5.700000,2025-03-12T23:00,23,동해,fggo3
온양,10.300000,2025-03-12T23:00,23,동해,byyh3
양양,7.700000,2025-03-12T23:00,23,동해,byy87
영덕,10.600000,2025-03-12T23:00,23,동해,byd8a
삼척,8.000000,2025-03-12T23:00,23,동해,bsc87

In [22]:
rawDfParse2.filter{gruNam.equals("동해") && wtrTmp_1 != null }
    .select{ staNamKor and wtrTmp_1 }
    .groupBy{staNamKor}
    .sortBy { staNamKor }
    .plot{
        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1600 to 600
        //    theme = Theme.HIGH_CONTRAST_DARK
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("staNamKor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }
    }

In [25]:
rawDfParse2
    .filter{wtrTmp_1 != null}
    .groupBy { staNamKor and "hour" }
    .aggregate {
        min{wtrTmp_1} into "min"
        max{wtrTmp_1} into "max"
        mean{wtrTmp_1} into "mean"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 1600 to 1200
        }

        ribbon {
            x("hour") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("staNamKor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(staNamKor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("hour")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 4.0..15.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 4) {
            facet(staNamKor)
        }
    }

In [24]:
rawDfParse2.filter{gruNam.equals("동해") && wtrTmp_1 != null }
    .select{ staNamKor and wtrTmp_1 and obsDtm }
    .plot{

        layout {
            title = "동해 해수 정보"
            size = 1600 to 600
        }

        x(obsDtm) { axis.name = "관측일시"}
        y(wtrTmp_1) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(staNamKor){
             //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

      //  facetWrap(nRow = 3){ facet(gruNam)   }

}

In [105]:
val url_East_Month = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=20250221&EDATE=20250227&numOfRows=100"

In [106]:
val rawEastMonthDf = load(url_East_Month, 200 )

Can not get nested column 'item' from ValueColumn 'items'

In [107]:
val rawEastMonthConcat = rawEastMonthDf.item.concat()

In [108]:
rawEastMonthConcat.writeJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [24]:
val rawEastMonthConcat = DataFrame.readJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [25]:
val rawEastMonthParse = rawEastMonthConcat.parse()

In [26]:
rawEastMonthParse.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000

In [27]:
val rawEastMonthParse2 = rawEastMonthParse.convert( "wtrTmp_1" ).toDouble()
    .add{
        "day" from obsDtm.map { it.dayOfMonth }
    }

rawEastMonthParse2.head()

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2,day
덕천,34.298000,2025-02-27T23:30,bdch3,233000,11.100000,동해,null,null,27
구룡포 하정,null,2025-02-27T23:30,fghe8,233000,10.400000,동해,null,null,27
고성 가진,null,2025-02-27T23:30,fggo3,233000,5.400000,동해,4.900000,5.300000,27
온양,34.359000,2025-02-27T23:30,byyh3,233000,10.000000,동해,null,null,27
영덕,null,2025-02-27T23:30,byd8a,233000,10.400000,동해,10.000000,10.200000,27

In [28]:
rawEastMonthParse2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000
day,Int,3955,7,0,23,576,23.971176,1.986214,21,24,27

In [29]:
rawEastMonthParse2.groupBy { staNamKor and "day" }
    .aggregate {
        min{wtrTmp_1} into "min"
        max{wtrTmp_1} into "max"
        mean{wtrTmp_1} into "mean"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 800 to 400
        }

        ribbon {

            x("day") {
                axis.name = "측정일"
            }

            y.axis {
                limits = 2.0..15.0
                name = "수온 최저~최고"
            }

            yMin("min")
            yMax("max")
            fillColor("staNamKor"){
                legend {
                    name = "관측지점"
                }
            }
            alpha = 0.6
            borderLine.width = 0.0

            tooltips(title = value(staNamKor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정일", day.tooltipValue("d"))
            }
        }


    }