In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [504]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250224"
val EDATE = "20250224"
val numOfRows = "100"
val maxPage = 6

In [424]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [641]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250224&EDATE=20250224&numOfRows=100

In [642]:
val df = load(url, maxPage)
df

Can not get nested column 'item' from ValueColumn 'items'

In [643]:
val df2 = df.item.concat()

In [644]:
val df3 = df2.parse()

In [645]:
df3

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2
덕천,34.302000,2025-02-24T17:30,bdch3,173000,12.400000,동해,null,null
구룡포 하정,null,2025-02-24T17:30,fghe8,173000,10.600000,동해,null,null
고성 가진,null,2025-02-24T17:30,fggo3,173000,5.600000,동해,5.200000,5.400000
온양,34.349000,2025-02-24T17:30,byyh3,173000,10.500000,동해,null,null
양양,null,2025-02-24T17:30,byy87,173000,5.500000,동해,5.500000,5.500000
영덕,null,2025-02-24T17:30,byd8a,173000,10.400000,동해,10.300000,10.300000
삼척,null,2025-02-24T17:30,bsc87,173000,9.500000,동해,9,9.100000
나곡,34.266000,2025-02-24T17:30,bngh3,173000,11.600000,동해,null,null
진하,34.318000,2025-02-24T17:30,bjhh3,173000,11.900000,동해,null,null
고리,35.241000,2025-02-24T17:30,bgrh3,173000,12.700000,동해,null,null
강릉,null,2025-02-24T17:30,bgna3,173000,7,동해,6.500000,6.700000
기장(한수원),34.498000,2025-02-24T17:30,bgjh3,173000,12.500000,동해,null,null
기장,null,2025-02-24T17:30,bgj8a,173000,12.300000,동해,12.300000,12.300000
기장,null,2025-02-24T17:00,bgj8a,170000,12.300000,동해,12.200000,12.300000
구룡포 하정,null,2025-02-24T17:00,fghe8,170000,10.700000,동해,null,null
고성 가진,null,2025-02-24T17:00,fggo3,170000,5.500000,동해,5.200000,5.400000
양양,null,2025-02-24T17:00,byy87,170000,5.500000,동해,5.500000,5.500000
영덕,null,2025-02-24T17:00,byd8a,170000,10.400000,동해,10.300000,10.300000
삼척,null,2025-02-24T17:00,bsc87,170000,9.500000,동해,9.100000,9.200000
강릉,null,2025-02-24T17:00,bgna3,170000,7,동해,6.500000,6.700000

In [646]:
df3.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,431,13,0,기장,40,null,null,강릉,나곡,진하
cdt_1,Double?,431,117,247,34.378000,5,34.500130,0.332322,34.235000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,431,36,0,2025-02-24T17:30,13,null,null,2025-02-24T00:00,2025-02-24T08:30,2025-02-24T17:30
staCde,String,431,13,0,bgj8a,40,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,431,36,0,173000,13,null,null,null,null,null
wtrTmp_1,Number,431,47,0,5.500000,42,9.864501,2.460368,5.400000,10.500000,13.000000
gruNam,String,431,1,0,동해,431,null,null,동해,동해,동해
wtrTmp_3,Number?,431,24,216,6.600000,24,8.250233,2.612262,5.100000,9.000000,12.400000
wtrTmp_2,Number?,431,22,216,5.500000,28,8.319070,2.588140,5.300000,9.000000,12.500000

In [654]:
df3.plot{
    x(obsDtm) { axis.name = "관측일시"}
    y(wtrTmp_1) {axis.name ="표층수온"}
    y.axis.limits = 0.0..15.0
    line{
        color(staNamKor){
            scale = continuous(Color.GREEN..Color.RED)
            legend{
                name = "관측소명"
            }
        }
    }

    layout {
        title = "동해 관측지점별 해수 정보"
        size = 1200 to 500
    }
}

In [455]:
df3.staNamKor.distinct()

staNamKor
덕천
구룡포 하정
고성 가진
온양
양양
영덕
삼척
나곡
진하
고리
강릉
기장(한수원)
기장

In [430]:
df3.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}

staCde,name,code,currentTemp
bdch3,덕천,bdch3,10.500000
fghe8,구룡포 하정,fghe8,9.900000
fggo3,고성 가진,fggo3,5.500000
byyh3,온양,byyh3,10.700000
byy87,양양,byy87,5.500000
byd8a,영덕,byd8a,10.600000
bsc87,삼척,bsc87,9.100000
bngh3,나곡,bngh3,10.300000
bjhh3,진하,bjhh3,11.800000
bgrh3,고리,bgrh3,11.900000
bgna3,강릉,bgna3,7.100000
bgjh3,기장(한수원),bgjh3,12.600000
bgj8a,기장,bgj8a,12.400000

In [525]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE.csv")
staCodeDf

gru,code,name,isavailable,enddate,latitude,longitude
동해,fggo3,고성 가진,사용,2024-03-11,38.368000,128.524000
동해,bgj8a,기장,사용,2008-11-04,35.187000,129.227000
동해,byy87,양양,사용,2008-07-13,38.082700,128.698400
동해,byd8a,영덕,사용,2008-11-04,36.573700,129.437000
동해,bgna3,강릉,사용,2008-07-08,37.799000,128.949200
동해,bsc87,삼척,사용,2008-07-22,37.302300,129.312700
동해,fgbg3,고성 봉포,사용,2016-03-10,38.249400,128.624500
동해,fghe8,구룡포 하정,사용,2014-08-08,35.960700,129.549700
동해,bgjh3,기장(한수원),사용,2017-04-03,35.182500,129.235200
동해,bgrh3,고리,사용,2017-04-03,35.318600,129.314700
동해,bjhh3,진하,사용,2017-04-03,35.384700,129.368000
동해,bjjh3,정자,사용,2017-04-03,35.634700,129.495000
동해,bysh3,월성,사용,2017-04-03,35.717700,129.495000
동해,byph3,양포,사용,2017-04-03,35.865800,129.547200
동해,byyh3,온양,사용,2017-04-03,37.019400,129.425000
동해,bdch3,덕천,사용,2017-04-03,37.100000,129.404100
동해,bngh3,나곡,사용,2017-04-03,37.119100,129.395800
서해,br001,보령 효자도,사용,2005-10-05,36.415800,126.433300
서해,sj086,서산 지곡,사용,2008-06-21,36.893500,126.352400
서해,fbn69,백령도,사용,2006-09-12,37.950500,124.729500

In [526]:
val df_currentMap = df3.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}.join(staCodeDf.select{ name and code and latitude and longitude}){
    "name" and "code"
}.remove { staCde }

df_currentMap

name,code,currentTemp,latitude,longitude
덕천,bdch3,10.500000,37.100000,129.404100
구룡포 하정,fghe8,9.900000,35.960700,129.549700
고성 가진,fggo3,5.500000,38.368000,128.524000
온양,byyh3,10.700000,37.019400,129.425000
양양,byy87,5.500000,38.082700,128.698400
영덕,byd8a,10.600000,36.573700,129.437000
삼척,bsc87,9.100000,37.302300,129.312700
나곡,bngh3,10.300000,37.119100,129.395800
진하,bjhh3,11.800000,35.384700,129.368000
고리,bgrh3,11.900000,35.318600,129.314700
강릉,bgna3,7.100000,37.799000,128.949200
기장(한수원),bgjh3,12.600000,35.182500,129.235200
기장,bgj8a,12.400000,35.187000,129.227000

In [433]:
df_currentMap.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
name,String,12,12,0,덕천,1,null,null,강릉,나곡,진하
code,String,12,12,0,bdch3,1,null,null,bdch3,bjhh3,fghe8
currentTemp,Number,12,12,0,10.500000,1,10.200000,2.122606,5.500000,10.550000,12.600000
latitude,Double,12,12,0,37.100000,1,36.502475,1.055060,35.182500,36.796550,38.082700
longitude,Double,12,12,0,129.404100,1,129.276400,0.235408,128.698400,129.341350,129.549700

In [434]:
%useLatestDescriptors
%use lets-plot
%use lets-plot-gt

In [435]:
import org.geotools.geojson.feature.FeatureJSON
val southKr = FeatureJSON().readFeatureCollection(File("/Users/unchil/Downloads/kr.json").readText())
val mapBound = southKr.bounds
mapBound.expandBy(0.2)

In [501]:
fun makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<Any?>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        properties.forEach { key, values ->
            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\",\n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t},\n"

    }

    return first_str + features_str + end_str
}

makePointGeoJSON( df_currentMap.map{Pair(longitude, latitude) }.toList(), df_currentMap.select{name and currentTemp}.toMap())

{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.4041, 37.1]
			},
			"properties": {
				"name": "덕천",
				"currentTemp": "10.5",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.5497, 35.9607]
			},
			"properties": {
				"name": "구룡포 하정",
				"currentTemp": "9.9",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.425, 37.0194]
			},
			"properties": {
				"name": "온양",
				"currentTemp": "10.7",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.6984, 38.0827]
			},
			"properties": {
				"name": "양양",
				"currentTemp": "5.5",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.437, 36.5737]
			},
			"properties": {
				"name": "영덕",
				"currentTemp": "10.6",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3127, 37.3023]
			},
			"properties": {
				"name": "삼척",
				"currentTemp": "9.1",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3958, 37.1191]
			},
			"properties": {
				"name": "나곡",
				"currentTemp": "10.3",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.368, 35.3847]
			},
			"properties": {
				"name": "진하",
				"currentTemp": "11.8",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3147, 35.3186]
			},
			"properties": {
				"name": "고리",
				"currentTemp": "11.9",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.9492, 37.799]
			},
			"properties": {
				"name": "강릉",
				"currentTemp": "7.1",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.2352, 35.1825]
			},
			"properties": {
				"name": "기장(한수원)",
				"currentTemp": "12.6",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.227, 35.187]
			},
			"properties": {
				"name": "기장",
				"currentTemp": "12.4",
			}
		},
	]
}

In [527]:
val point = FeatureJSON().readFeatureCollection(makePointGeoJSON( df_currentMap.map{Pair(longitude, latitude) }.toList(), df_currentMap.select{name and currentTemp}.toMap()))

In [537]:
letsPlot() +
        geomMap(map = southKr.toSpatialDataset() , color = "#a1d99b", fill = "#e5f5e0" ) +
        geomRect(xmin= mapBound.minX, xmax =mapBound.maxX, ymax=mapBound.maxY, ymin= mapBound.minY, alpha = 0, fill = "black", color="#EFC623", size=16) +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        geomPoint(map=point.toSpatialDataset() , size=3,  shape = 21,  fill = "red", tooltips = layerTooltips().title("@name").line("현재 수온:@currentTemp°C")) +
        geomText(map=point.toSpatialDataset() ,   position = positionNudge(x = +.2) , color="yellow"){ label =  "currentTemp"} +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = -.2) , color="black"){ label = "name" } +
        theme(panelBackground = elementRect(color = "black", fill = "#537ab5")) +
        ggtitle("Korea EastSeaWater Quality") +
        ggsize( width = 1000, height = 900)

In [634]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.WEST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
val instantLoadDf = load(url, 20)

Can not get nested column 'item' from ValueColumn 'items'

In [635]:
val instantTempDf = instantLoadDf.item.concat()
val tempDf = instantTempDf.parse()
tempDf

staNamKor,cdt_1,obsDtm,staCde,dox_1,obsTim,wtrTmp_1,gruNam,dox_2,wtrTmp_2
태안 고남,31.100000,2025-02-24T17:30,br001,11.300000,173000,3.900000,서해,null,null
서산 지곡,null,2025-02-24T17:30,sj086,null,173000,2.700000,서해,null,null
태안 파도리,null,2025-02-24T17:30,ftpk5,null,173000,2.900000,서해,13.900000,2.800000
태안 대야도,null,2025-02-24T17:30,ftdk5,11.700000,173000,4,서해,null,3.900000
서산 창리,31.700000,2025-02-24T17:30,fsch6,12.900000,173000,3.100000,서해,null,3.100000
해남 임하,null,2025-02-24T17:30,fjh5a,null,173000,5.500000,서해,null,null
진도 전두,null,2025-02-24T17:30,fjdfc,9.100000,173000,5.800000,서해,null,5.700000
백령도,null,2025-02-24T17:30,fbn69,null,173000,3.800000,서해,null,null
신안 압해,null,2025-02-24T17:30,esafc,13,173000,4.300000,서해,null,null
목포,null,2025-02-24T17:30,emp67,null,173000,5,서해,null,null
군산 신시도,null,2025-02-24T17:30,egsi4,null,173000,3.500000,서해,null,null
태안 고남,31.100000,2025-02-24T17:00,br001,11.200000,170000,3.900000,서해,null,null
서산 지곡,null,2025-02-24T17:00,sj086,null,170000,2.700000,서해,null,null
태안 파도리,null,2025-02-24T17:00,ftpk5,null,170000,3,서해,13.800000,2.900000
태안 대야도,null,2025-02-24T17:00,ftdk5,11.600000,170000,4,서해,null,3.900000
신안 하의,null,2025-02-24T17:00,fsuj7,null,null,4.900000,서해,null,null
신안 소신,null,2025-02-24T17:00,fssoc,null,null,4.600000,서해,null,null
신안 송공,null,2025-02-24T17:00,fssm6,null,null,4.200000,서해,null,null
신안 마리,null,2025-02-24T17:00,fsmm6,null,null,7.400000,서해,null,null
신안 장산,null,2025-02-24T17:00,fsjo4,null,null,5.500000,서해,null,null

In [627]:
val startDateTime = LocalDateTime(2025, 2, 24, 6, 0, 0)
val endDateTime  = LocalDateTime(2025, 2, 24, 14, 0, 0)

In [637]:
tempDf
   // .filter{ staNamKor.startsWith("거제") && obsDtm >= startDateTime && obsDtm <= endDateTime}
    .plot{
        x(obsDtm) {
            axis.name = "관측일시"
        }
        y(wtrTmp_1) {
            axis.name ="표층수온"
        }
        y.axis.limits = 0.0..15.0


        line{
            color(staNamKor){
                scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }
        layout {
            title = "서해 관측지점별 해수 정보"
            size = 1200 to 600
        }
    }

In [638]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.SOUTH.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
val instantLoadDf = load(url, 20)

In [639]:
val instantTempDf = instantLoadDf.item.concat()
val tempDf = instantTempDf.parse()
tempDf

staNamKor,obsDtm,staCde,dox_1,obsTim,wtrTmp_1,gruNam,wtrTmp_2,cdt_1,wtrTmp_3,dox_3,dox_2
장흥 회진,2025-02-24T17:30,ejhfc,12.800000,173000,6.600000,남해,6.600000,null,null,null,null
완도 노화도,2025-02-24T17:30,wn087,null,173000,6.700000,남해,null,null,null,null,null
완도 금일,2025-02-24T17:30,wk094,null,173000,7.700000,남해,null,null,null,null,null
완도 청산,2025-02-24T17:30,wc001,10.900000,173000,8.300000,남해,null,null,null,null,null
통영 사량,2025-02-24T17:30,ty005,10.200000,173000,8.100000,남해,null,null,null,null,null
통영 영운,2025-02-24T17:30,ty004,null,173000,8.700000,남해,null,null,null,null,null
통영 비산도,2025-02-24T17:30,tb087,11.200000,173000,7.200000,남해,7,null,null,null,null
여수 신월,2025-02-24T17:30,km001,11,173000,4.200000,남해,null,null,null,null,null
거제 일운,2025-02-24T17:30,gi086,9.200000,173000,10.300000,남해,null,null,null,null,null
완도 감목,2025-02-24T17:30,fwyo5,10.100000,173000,7.800000,남해,null,null,null,null,null
완도 사동,2025-02-24T17:30,fwso5,null,173000,6.300000,남해,null,null,null,null,null
완도 망남,2025-02-24T17:30,fwmg3,13.400000,173000,6.900000,남해,7,null,null,null,null
완도 일정,2025-02-24T17:30,fwih6,null,173000,8,남해,null,null,null,null,null
완도 가교,2025-02-24T17:30,fwgf1,13.200000,173000,5.400000,남해,5.400000,null,null,null,null
완도 대창,2025-02-24T17:30,fwdo5,null,173000,4.600000,남해,null,null,null,null,null
완도 동백,2025-02-24T17:30,fwdf1,12.400000,173000,7.600000,남해,7.600000,null,null,null,null
완도 백도,2025-02-24T17:30,fwbf1,13.900000,173000,6.700000,남해,6.700000,null,null,null,null
통영 수월,2025-02-24T17:30,ftsj3,10.300000,173000,8.400000,남해,null,33.600000,null,null,null
통영 풍화,2025-02-24T17:30,ftp4c,null,173000,8.700000,남해,8.600000,null,null,null,null
통영 학림,2025-02-24T17:30,fth59,9.100000,173000,9.400000,남해,9.400000,null,9.300000,null,null

In [640]:
tempDf
    // .filter{ staNamKor.startsWith("거제") && obsDtm >= startDateTime && obsDtm <= endDateTime}
    .plot{
        x(obsDtm) {
            axis.name = "관측일시"
        }
        y(wtrTmp_1) {
            axis.name ="표층수온"
        }
        y.axis.limits = 0.0..15.0


        line{
            color(staNamKor){
                scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }
        layout {
            title = "남해 관측지점별 해수 정보"
            size = 1200 to 600
        }
    }