In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [740]:
val EndPoint = "http://apis.data.go.kr/1520635/OceanMensurationService"
val servicePath = "getOceanMesurationListrisa"
val servicePath2 = "getOceanMesurationDetailrisa"
val EncodingKey = "5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D"
val SDATE = "20250225"
val EDATE = "20250225"
val numOfRows = "100"
val maxPage = 10

In [424]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [771]:
val url = "$EndPoint/$servicePath?ServiceKey=$EncodingKey&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"
url

http://apis.data.go.kr/1520635/OceanMensurationService/getOceanMesurationListrisa?ServiceKey=5n1IN38zxdvnUX9sRlSNdTG9xdkLV3gLzBVEuFn9zjdols8ci8U6V%2F7GeZDujqbHE4KShW0iI6%2BR50vGP7j9CA%3D%3D&GRU_NAM=001&SDATE=20250225&EDATE=20250225&numOfRows=100

In [772]:
val rawDf = load(url, maxPage)
rawDf

Can not get nested column 'item' from ValueColumn 'items'

In [773]:
val rawDfConcat = rawDf.item.concat()

In [774]:
val rawDfParse = rawDfConcat.parse()

In [775]:
rawDfParse

staNamKor,obsDtm,staCde,obsTim,wtrTmp_3,wtrTmp_1,gruNam,wtrTmp_2,cdt_1
기장,2025-02-25T09:00,bgj8a,90000,12.200000,12.100000,동해,12.200000,null
구룡포 하정,2025-02-25T09:00,fghe8,90000,null,9.900000,동해,null,null
고성 가진,2025-02-25T09:00,fggo3,90000,5.200000,5.400000,동해,5.300000,null
양양,2025-02-25T09:00,byy87,90000,5.300000,5.300000,동해,5.300000,null
영덕,2025-02-25T09:00,byd8a,90000,10.200000,10.200000,동해,10.100000,null
삼척,2025-02-25T09:00,bsc87,90000,8.600000,8.900000,동해,8.900000,null
고리,2025-02-25T09:00,bgrh3,90000,null,13.600000,동해,null,35.262000
강릉,2025-02-25T09:00,bgna3,90000,6.400000,6.500000,동해,6.500000,null
덕천,2025-02-25T08:30,bdch3,83000,null,10.700000,동해,null,34.356000
구룡포 하정,2025-02-25T08:30,fghe8,83000,null,9.800000,동해,null,null
고성 가진,2025-02-25T08:30,fggo3,83000,5.200000,5.400000,동해,5.300000,null
온양,2025-02-25T08:30,byyh3,83000,null,10.100000,동해,null,34.335000
양양,2025-02-25T08:30,byy87,83000,5.300000,5.300000,동해,5.300000,null
영덕,2025-02-25T08:30,byd8a,83000,10.200000,10.200000,동해,10.100000,null
삼척,2025-02-25T08:30,bsc87,83000,8.300000,8.900000,동해,8.900000,null
나곡,2025-02-25T08:30,bngh3,83000,null,10.700000,동해,null,34.314000
진하,2025-02-25T08:30,bjhh3,83000,null,11.800000,동해,null,34.305000
고리,2025-02-25T08:30,bgrh3,83000,null,12.800000,동해,null,35.326000
강릉,2025-02-25T08:30,bgna3,83000,6.400000,6.500000,동해,6.600000,null
기장(한수원),2025-02-25T08:30,bgjh3,83000,null,12.300000,동해,null,34.495000

In [776]:
rawDfParse.staNamKor.distinct()

staNamKor
기장
구룡포 하정
고성 가진
양양
영덕
삼척
고리
강릉
덕천
온양
나곡
진하
기장(한수원)

In [777]:
rawDfParse.plot{
    x(obsDtm) { axis.name = "관측일시"}
    y(wtrTmp_1) {axis.name ="표층수온"}
    y.axis.limits = 0.0..15.0
    line{
        color(staNamKor){
            scale = continuous(Color.GREEN..Color.RED)
            legend{
                name = "관측소명"
            }
        }
    }

    layout {
        title = "동해 관측지점별 해수 정보"
        size = 1200 to 500
    }
}

In [778]:
rawDfParse.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}

staCde,name,code,currentTemp
bgj8a,기장,bgj8a,12.100000
fghe8,구룡포 하정,fghe8,9.900000
fggo3,고성 가진,fggo3,5.400000
byy87,양양,byy87,5.300000
byd8a,영덕,byd8a,10.200000
bsc87,삼척,bsc87,8.900000
bgrh3,고리,bgrh3,13.600000
bgna3,강릉,bgna3,6.500000
bdch3,덕천,bdch3,10.700000
byyh3,온양,byyh3,10.100000
bngh3,나곡,bngh3,10.700000
bjhh3,진하,bjhh3,11.800000
bgjh3,기장(한수원),bgjh3,12.300000

In [779]:
val staCodeDf = DataFrame.readCSV("/Volumes/WorkSpace/Notebook/data/STA_CODE_NEW2.csv")
staCodeDf

staCde,gruNam,name,longitude,latitude
fgmk6,남해,강진 마량,126.813286,34.444798
fgsl6,남해,강진 사초,126.769100,34.459900
ms002,남해,거제,128.458900,34.535900
fgg4c,남해,거제 가배,128.566400,34.785100
fggj7,남해,거제 가조,128.514200,34.977200
gi086,남해,거제 일운,128.709400,34.803800
btei5,남해,거제 해금강,128.690833,34.735833
bgyga,남해,고성 용정,128.500860,34.989700
bgjgb,남해,고성 장좌,128.465450,34.970800
ys002,남해,고흥,127.350900,34.261200
fggm6,남해,고흥 금산,127.097000,34.452600
fgnm6,남해,고흥 남열,127.465600,34.571300
fgdl4,남해,고흥 동촌,127.225800,34.433000
fgpo4,남해,고흥 발포,127.370100,34.441600
bgui5,남해,고흥 부아도,127.178611,34.375278
fgbo4,남해,고흥 비사도,127.455700,34.557900
fgsj3,남해,고흥 소록도,127.122800,34.504900
fgso4,남해,고흥 시산,127.277600,34.384700
fgsl4,남해,고흥 신촌,127.101700,34.473800
fgyl4,남해,고흥 연소,127.118100,34.436500

In [786]:
val df = rawDfParse.groupBy{staCde}.aggregate {
    val currentData = maxBy{obsDtm}
    currentData.obsDtm into "datetime"
    currentData.gruNam into "gruNam"
    currentData.staNamKor into "name"
    currentData.staCde into "code"
    currentData.wtrTmp_1 into "currentTemp"
}.join(staCodeDf.select{  gruNam and  name and staCde and latitude and longitude}){
     "gruNam" and "name" and "staCde"
}.remove { staCde }

df

datetime,gruNam,name,code,currentTemp,latitude,longitude
2025-02-25T09:00,동해,기장,bgj8a,12.100000,35.187000,129.227000
2025-02-25T09:00,동해,구룡포 하정,fghe8,9.900000,35.960700,129.549700
2025-02-25T09:00,동해,고성 가진,fggo3,5.400000,38.368100,128.523900
2025-02-25T09:00,동해,양양,byy87,5.300000,38.080800,128.699800
2025-02-25T09:00,동해,영덕,byd8a,10.200000,36.573700,129.437000
2025-02-25T09:00,동해,삼척,bsc87,8.900000,37.302300,129.312700
2025-02-25T09:00,동해,고리,bgrh3,13.600000,35.318600,129.314700
2025-02-25T09:00,동해,강릉,bgna3,6.500000,37.799000,128.949200
2025-02-25T08:30,동해,덕천,bdch3,10.700000,37.100000,129.404100
2025-02-25T08:30,동해,온양,byyh3,10.100000,37.019400,129.425000
2025-02-25T08:30,동해,나곡,bngh3,10.700000,37.119100,129.395800
2025-02-25T08:30,동해,진하,bjhh3,11.800000,35.384700,129.368000
2025-02-25T08:30,동해,기장(한수원),bgjh3,12.300000,35.182500,129.235200

In [781]:
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
gruNam,String,13,1,0,동해,13,null,null,동해,동해,동해
name,String,13,13,0,기장,1,null,null,강릉,나곡,진하
code,String,13,13,0,bgj8a,1,null,null,bdch3,bngh3,fghe8
currentTemp,Number,13,12,0,10.700000,2,9.807692,2.632635,5.300000,10.200000,13.600000
latitude,Double,13,13,0,35.187000,1,36.645838,1.134755,35.182500,37.019400,38.368100
longitude,Double,13,13,0,129.227000,1,129.218623,0.306979,128.523900,129.314700,129.549700

In [754]:
%useLatestDescriptors
%use lets-plot
%use lets-plot-gt

In [435]:
import org.geotools.geojson.feature.FeatureJSON
val southKr = FeatureJSON().readFeatureCollection(File("/Users/unchil/Downloads/kr.json").readText())
val mapBound = southKr.bounds
mapBound.expandBy(0.2)

In [796]:
fun makePointGeoJSON( coordinates:List<Pair<Double, Double>>, properties:Map<String, List<Any?>>): String {
    val first_str = "{" + "\n" +
            "\t\"type\": \"FeatureCollection\"," + "\n" +
            "\t\"features\": [" + "\n"

    val end_str = "\t]" + "\n" +
            "}" + "\n"

    var features_str = ""

    coordinates.forEachIndexed { index,    pair ->

        features_str += "\t\t{\n" +
                "\t\t\t\"type\": \"Feature\",\n" +
                "\t\t\t\"geometry\": {\n" +
                "\t\t\t\t\"type\": \"Point\",\n" +
                "\t\t\t\t\"coordinates\": [${pair.first}, ${pair.second}]\n" +
                "\t\t\t},\n" +
                "\t\t\t\"properties\": {\n"

        properties.forEach { key, values ->
            features_str += "\t\t\t\t\"${key}\": \"${values[index]}\",\n"
        }

        features_str +=  "\t\t\t}\n" + "\t\t},\n"

    }

    return first_str + features_str + end_str
}

makePointGeoJSON( df.select{longitude and latitude}.map{ Pair(longitude, latitude) }.toList(), df.select{name and currentTemp and datetime }.toMap())

{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.227, 35.187]
			},
			"properties": {
				"name": "기장",
				"currentTemp": "12.1",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.5497, 35.9607]
			},
			"properties": {
				"name": "구룡포 하정",
				"currentTemp": "9.9",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.5239, 38.3681]
			},
			"properties": {
				"name": "고성 가진",
				"currentTemp": "5.4",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.6998, 38.0808]
			},
			"properties": {
				"name": "양양",
				"currentTemp": "5.3",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.437, 36.5737]
			},
			"properties": {
				"name": "영덕",
				"currentTemp": "10.2",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3127, 37.3023]
			},
			"properties": {
				"name": "삼척",
				"currentTemp": "8.9",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3147, 35.3186]
			},
			"properties": {
				"name": "고리",
				"currentTemp": "13.6",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [128.9492, 37.799]
			},
			"properties": {
				"name": "강릉",
				"currentTemp": "6.5",
				"datetime": "2025-02-25T09:00",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.4041, 37.1]
			},
			"properties": {
				"name": "덕천",
				"currentTemp": "10.7",
				"datetime": "2025-02-25T08:30",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.425, 37.0194]
			},
			"properties": {
				"name": "온양",
				"currentTemp": "10.1",
				"datetime": "2025-02-25T08:30",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.3958, 37.1191]
			},
			"properties": {
				"name": "나곡",
				"currentTemp": "10.7",
				"datetime": "2025-02-25T08:30",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.368, 35.3847]
			},
			"properties": {
				"name": "진하",
				"currentTemp": "11.8",
				"datetime": "2025-02-25T08:30",
			}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [129.2352, 35.1825]
			},
			"properties": {
				"name": "기장(한수원)",
				"currentTemp": "12.3",
				"datetime": "2025-02-25T08:30",
			}
		},
	]
}

In [797]:
val point = FeatureJSON().readFeatureCollection(makePointGeoJSON( df.select{longitude and latitude}.map{Pair(longitude, latitude) }.toList(), df.select{name and currentTemp and datetime}.toMap()))

In [798]:
letsPlot() +
        geomMap(map = southKr.toSpatialDataset() , color = "#a1d99b", fill = "#e5f5e0" ) +
        geomRect(xmin= mapBound.minX, xmax =mapBound.maxX, ymax=mapBound.maxY, ymin= mapBound.minY, alpha = 0, fill = "black", color="#EFC623", size=6) +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        geomPoint(map=point.toSpatialDataset() , size=3,  shape = 21,  fill = "red", tooltips = layerTooltips().title("@name").line("수온:@currentTemp°C\n@datetime")) +
        geomText(map=point.toSpatialDataset() ,   position = positionNudge(x = +.2) , color="yellow"){ label =  "currentTemp"} +
        geomText(map=point.toSpatialDataset() , position = positionNudge(x = -.2) , color="black"){ label = "name" } +
        theme(panelBackground = elementRect(color = "black", fill = "#537ab5")) +
        ggtitle("Korea EastSea Water Quality") +
        ggsize( width = 1000, height = 1000)