In [1]:
%useLatestDescriptors
%use dataframe
%use kandy

In [2]:
USE{
    dependencies("org.json:json:20250107")
}

In [3]:
import org.json.XML

In [4]:
enum class SeaSector(val simpleName: String) {
    EAST("001"),
    WEST("002"),
    SOUTH("003")
}

In [5]:
val serviceKeyFilePath = "/Volumes/WorkSpace/Notebook/data/OceanMensurationService.json"
val SDATE = "20250228"
val EDATE = "20250228"
val numOfRows = "100"
val maxPage = 500

In [6]:
fun load(path:String, maxPage:Int): AnyFrame {
    val rows = mutableListOf<AnyFrame>()
    var requestPage = 1
    do{
        val pagePath = "$path&pageNo=$requestPage"
        val jsonData = XML.toJSONObject(DataFrame.read(pagePath).toString())
        val df = DataFrame.readJson(jsonData.toString().byteInputStream())
        try {
            val instanceDf = df.get("response").get("body").get("items").get("item").toDataFrame()
            requestPage += 1
            rows.add(instanceDf)
        } catch(e: Exception) {
            print(e.localizedMessage)
            break
        }
    } while (rows.size < maxPage )
    return rows.concat()
}

In [7]:
val serviceInfo = DataRow.readJson(path=serviceKeyFilePath)

In [8]:
val url_East = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [9]:
val url_West = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.WEST.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [10]:
val url_South = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.SOUTH.simpleName}&SDATE=$SDATE&EDATE=$EDATE&numOfRows=$numOfRows"

In [11]:
val rawEastDf = load(url_East,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [12]:
val rawEastConcat = rawEastDf.item.concat()

In [13]:
rawEastConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,522,12,0,기장,53,null,null,강릉,기장(한수원),진하
cdt_1,Double?,522,150,287,34.328000,5,34.466013,0.312847,34.147000,34.333000,35.184000
obsDtm,String,522,48,0,2025-02-28 23:30:00,12,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,522,12,0,bgj8a,53,null,null,bdch3,bngh3,fghe8
obsTim,Comparable<*>,522,48,0,233000,12,null,null,null,null,null
wtrTmp_1,Number,522,54,0,11.700000,52,10.177203,1.845854,5.400000,10.400000,13.400000
gruNam,String,522,1,0,동해,522,null,null,동해,동해,동해
wtrTmp_3,Number?,522,42,278,10,46,8.277869,2.545439,4.500000,8.800000,11.800000
wtrTmp_2,Number?,522,40,278,10,43,8.703279,2.253573,5.100000,9.150000,11.800000

In [14]:
val rawWestDf = load(url_West,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [15]:
val rawWestConcat = rawWestDf.item.concat()

In [16]:
rawWestConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,961,30,0,군산 신시도,57,null,null,군산 신시도,신안 송공,해남 임하
cdt_1,Number?,961,9,866,31,31,31.312632,0.299731,30.900000,31.200000,31.700000
obsDtm,String,961,48,0,2025-02-28 20:00:00,30,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,961,30,0,egsi4,57,null,null,br001,fjoo4,sj086
dox_1,Number?,961,31,720,9,37,11.761411,1.632395,8.900000,12.200000,13.800000
obsTim,Comparable<*>?,961,49,428,210000,13,null,null,null,null,null
wtrTmp_1,Number,961,60,0,4.100000,60,5.436629,1.281060,3.500000,5.400000,13.100000
gruNam,String,961,1,0,서해,961,null,null,서해,서해,서해
dox_2,Number?,961,11,920,13.100000,17,13.426829,0.356388,13.100000,13.200000,14.000000
wtrTmp_2,Number?,961,22,782,6.100000,18,4.587709,0.997167,3.500000,4.100000,6.400000

In [17]:
val rawSouthDf = load(url_South,maxPage )

Can not get nested column 'item' from ValueColumn 'items'

In [18]:
val rawSouthConcat = rawSouthDf.item.concat()

In [19]:
rawSouthConcat.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,2882,101,0,서제주,74,null,null,강진 마량,완도 노화도,해남 황산
obsDtm,String,2882,48,0,2025-02-28 18:00:00,99,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,2882,101,0,ejj47,74,null,null,ejhfc,fjil6,wn087
dox_1,Number?,2882,46,2219,10.100000,71,11.138311,1.307500,9.000000,11.000000,13.700000
obsTim,Comparable<*>?,2882,49,1637,000000,35,null,null,null,null,null
wtrTmp_1,Number,2882,72,0,7.600000,180,7.354997,1.571385,4.700000,7.200000,14.100000
gruNam,String,2882,1,0,남해,2882,null,null,남해,남해,남해
wtrTmp_2,Number?,2882,39,2341,7.600000,48,7.492421,1.060939,5.200000,7.600000,9.300000
cdt_1,Double?,2882,7,2688,34.800000,73,33.782990,0.853259,32.800000,33.600000,34.900000
wtrTmp_3,Double?,2882,12,2773,9.200000,36,7.908257,1.330422,6.400000,7.800000,9.300000
dox_3,Number?,2882,9,2827,10.600000,13,11.714545,0.819308,10.600000,11.700000,13.000000
dox_2,Number?,2882,14,2827,11.800000,10,11.710909,0.821172,10.500000,11.700000,13.100000

In [20]:
val rawDf = listOf(rawEastConcat, rawWestConcat, rawSouthConcat).concat()

In [21]:
rawDf.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,4365,143,0,서제주,74,null,null,강릉,여수 신월,해남 황산
cdt_1,Number?,4365,164,3841,34.800000,73,33.641437,1.275409,30.900000,34.277000,35.184000
obsDtm,String,4365,48,0,2025-02-28 18:00:00,141,null,null,2025-02-28 00:00:00,2025-02-28 12:00:00,2025-02-28 23:30:00
staCde,String,4365,143,0,ejj47,74,null,null,bdch3,fhso4,wn087
obsTim,Comparable<*>?,4365,49,2065,000000,58,null,null,null,null,null
wtrTmp_1,Number,4365,107,0,7.600000,181,7.270149,2.038097,3.500000,7.000000,14.100000
gruNam,String,4365,3,0,남해,2882,null,null,남해,남해,서해
wtrTmp_3,Number?,4365,44,4012,10,46,8.163739,2.246156,4.500000,8.800000,11.800000
wtrTmp_2,Number?,4365,62,3401,7.600000,50,7.259544,1.995494,3.500000,7.300000,11.800000
dox_1,Number?,4365,49,3461,10.100000,71,11.304425,1.427418,8.900000,11.300000,13.800000
dox_2,Number?,4365,23,4269,13.100000,19,12.443750,1.079260,10.500000,12.900000,14.000000
dox_3,Number?,4365,9,4310,10.600000,13,11.714545,0.819308,10.600000,11.700000,13.000000

In [22]:
val rawDfParse = rawDf.parse()

In [23]:
rawDfParse.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,4365,143,0,서제주,74,null,null,강릉,여수 신월,해남 황산
cdt_1,Number?,4365,164,3841,34.800000,73,33.641437,1.275409,30.900000,34.277000,35.184000
obsDtm,kotlinx.datetime.LocalDateTime,4365,48,0,2025-02-28T18:00,141,null,null,2025-02-28T00:00,2025-02-28T12:00,2025-02-28T23:30
staCde,String,4365,143,0,ejj47,74,null,null,bdch3,fhso4,wn087
obsTim,Comparable<*>?,4365,49,2065,000000,58,null,null,null,null,null
wtrTmp_1,Number,4365,107,0,7.600000,181,7.270149,2.038097,3.500000,7.000000,14.100000
gruNam,String,4365,3,0,남해,2882,null,null,남해,남해,서해
wtrTmp_3,Number?,4365,44,4012,10,46,8.163739,2.246156,4.500000,8.800000,11.800000
wtrTmp_2,Number?,4365,62,3401,7.600000,50,7.259544,1.995494,3.500000,7.300000,11.800000
dox_1,Number?,4365,49,3461,10.100000,71,11.304425,1.427418,8.900000,11.300000,13.800000
dox_2,Number?,4365,23,4269,13.100000,19,12.443750,1.079260,10.500000,12.900000,14.000000
dox_3,Number?,4365,9,4310,10.600000,13,11.714545,0.819308,10.600000,11.700000,13.000000

In [40]:
val rawDfParse2 = rawDfParse.convert( "wtrTmp_1" ).toDouble()
    .add{
        "hour" from obsDtm.map { it.hour }
    }.select{
        "staNamKor" and "wtrTmp_1" and "obsDtm" and "hour" and "gruNam" and "staCde"
    }
rawDfParse2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,4365,143,0,서제주,74,null,null,강릉,여수 신월,해남 황산
wtrTmp_1,Double,4365,107,0,7.600000,181,7.270149,2.038097,3.500000,7.000000,14.100000
obsDtm,kotlinx.datetime.LocalDateTime,4365,48,0,2025-02-28T18:00,141,null,null,2025-02-28T00:00,2025-02-28T12:00,2025-02-28T23:30
hour,Int,4365,24,0,18,190,11.542268,6.886194,0,12,23
gruNam,String,4365,3,0,남해,2882,null,null,남해,남해,서해
staCde,String,4365,143,0,ejj47,74,null,null,bdch3,fhso4,wn087

In [72]:
// Time series data at 30-minute intervals for one day
rawDfParse2.groupBy{gruNam and staNamKor}.count()

gruNam,staNamKor,count
동해,덕천,40
동해,구룡포 하정,43
동해,고성 가진,45
동해,온양,36
동해,영덕,47
동해,삼척,48
동해,나곡,43
동해,진하,35
동해,고리,40
동해,강릉,51
동해,기장(한수원),41
동해,기장,53
서해,태안 고남,48
서해,서산 지곡,39
서해,태안 파도리,41
서해,태안 대야도,41
서해,서산 창리,47
서해,해남 임하,49
서해,진도 전두,50
서해,백령도,52

In [128]:
val timeZone = TimeZone.of("UTC+0")
val startDate = LocalDateTime(2025, 2, 28, 0, 0)
val endDate = LocalDateTime(2025, 2, 28, 23, 31)
val intervalMinute = 30

val date = generateSequence(startDate.toInstant(timeZone)){
        it.plus(intervalMinute, DateTimeUnit.MINUTE, timeZone) }
    .takeWhile { it  <= endDate.toInstant(timeZone) }
    .toList()

val dateDf = dataFrameOf("date" to date)
dateDf.describe()

name,type,count,unique,nulls,top,freq,min,median,max
date,kotlinx.datetime.Instant,48,48,0,2025-02-28T00:00:00Z,1,2025-02-28T00:00:00Z,2025-02-28T11:30:00Z,2025-02-28T23:30:00Z

In [25]:
rawDfParse2.filter{gruNam.equals("동해") }
    .select{ staNamKor and wtrTmp_1 }
    .groupBy{staNamKor}
    .sortBy { staNamKor }
    .plot{
        layout {
            title = "관측지점별 일평균 해수 정보"
            size = 1400 to 600
        //    theme = Theme.HIGH_CONTRAST_DARK
        }

        boxplot("staNamKor", "wtrTmp_1") {
            boxes {
                borderLine.color = Color.BLUE
                fillColor("staNamKor"){
                    scale = categoricalColorHue()
                    legend{
                        name= "관측 지점"
                    }
                }
            }
        }
    }

In [28]:
rawDfParse2
    .filter{staNamKor in listOf("고리", "나곡", "덕천", "구룡포 하정")}
    .groupBy { staNamKor and "hour" }
    .aggregate {
        min{wtrTmp_1} into "min"
        max{wtrTmp_1} into "max"
        mean{wtrTmp_1} into "mean"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 1200 to 800
        }

        ribbon {
            x("hour") {
                axis.name = "측정시간"
            }

            yMin("min")
            yMax("max")

            alpha = 0.6
            borderLine.width = 0.0
            fillColor("staNamKor"){
                legend {
                    name = "관측지점"
                }
            }

            tooltips(title = value(staNamKor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정시간", hour.tooltipValue("d"))
            }
        }

        line {
            x("hour")
            y("mean")
            width = 1.0
            color = Color.BLUE
            tooltips(enable=false)
        }

        y.axis {
            limits = 8.0..15.0
            name = "수온 최저~최고"
        }

        facetWrap(nCol = 2) {
            facet(staNamKor)
        }
    }

In [35]:
rawDfParse2.filter{gruNam.equals("동해")  }
    .select{ staNamKor and wtrTmp_1 and obsDtm }
    .plot{

        layout {
            title = "남해 해수 정보"
            size = 1400 to 600
        }

        x(obsDtm) { axis.name = "관측일시"}
        y(wtrTmp_1) {axis.name ="표층수온"}
        y.axis.limits = 2.0..15.0
        line{
            color(staNamKor){
             //   scale = continuous(Color.GREEN..Color.RED)
                legend{
                    name = "관측소명"
                }
            }
        }

      //  facetWrap(nRow = 3){ facet(gruNam)   }

}

In [105]:
val url_East_Month = "${serviceInfo.endpoint_apis}/${serviceInfo.list_apis}?ServiceKey=${serviceInfo.key_apis}&GRU_NAM=${SeaSector.EAST.simpleName}&SDATE=20250221&EDATE=20250227&numOfRows=100"

In [106]:
val rawEastMonthDf = load(url_East_Month, 200 )

Can not get nested column 'item' from ValueColumn 'items'

In [107]:
val rawEastMonthConcat = rawEastMonthDf.item.concat()

In [108]:
rawEastMonthConcat.writeJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [3]:
val rawEastMonthConcat = DataFrame.readJson("/Volumes/WorkSpace/Notebook/data/21_27.json")

In [9]:
val rawEastMonthParse = rawEastMonthConcat.parse()

In [5]:
rawEastMonthParse.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000

In [128]:
val rawEastMonthParse2 = rawEastMonthParse.convert( "wtrTmp_1" ).toDouble()
    .add{
        "day" from obsDtm.map { it.dayOfMonth }
    }

rawEastMonthParse2.head()

staNamKor,cdt_1,obsDtm,staCde,obsTim,wtrTmp_1,gruNam,wtrTmp_3,wtrTmp_2,day
덕천,34.298000,2025-02-27T23:30,bdch3,233000,11.100000,동해,null,null,27
구룡포 하정,null,2025-02-27T23:30,fghe8,233000,10.400000,동해,null,null,27
고성 가진,null,2025-02-27T23:30,fggo3,233000,5.400000,동해,4.900000,5.300000,27
온양,34.359000,2025-02-27T23:30,byyh3,233000,10.000000,동해,null,null,27
영덕,null,2025-02-27T23:30,byd8a,233000,10.400000,동해,10.000000,10.200000,27

In [129]:
rawEastMonthParse2.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,median,max
staNamKor,String,3955,13,0,기장,362,null,null,강릉,나곡,진하
cdt_1,Double?,3955,339,2264,34.305000,21,34.487417,0.321047,34.213000,34.343000,35.345000
obsDtm,kotlinx.datetime.LocalDateTime,3955,336,0,2025-02-26T20:30,13,null,null,2025-02-21T00:00,2025-02-24T11:00,2025-02-27T23:30
staCde,String,3955,13,0,bgj8a,362,null,null,bdch3,bngh3,fghe8
obsTim,Int,3955,48,0,203000,90,116259.924147,68934.903643,0,120000,233000
wtrTmp_1,Double,3955,73,0,12.100000,154,9.903110,2.325180,5.200000,10.500000,13.800000
gruNam,String,3955,1,0,동해,3955,null,null,동해,동해,동해
wtrTmp_3,Double?,3955,75,1999,5.300000,100,8.249744,2.550042,4.600000,8.500000,12.500000
wtrTmp_2,Double?,3955,60,1999,5.300000,141,8.396217,2.492433,5.100000,8.900000,12.500000
day,Int,3955,7,0,23,576,23.971176,1.986214,21,24,27

In [132]:
rawEastMonthParse2.groupBy { staNamKor and "day" }
    .aggregate {
        min{wtrTmp_1} into "min"
        max{wtrTmp_1} into "max"
        mean{wtrTmp_1} into "mean"
    }
    .plot{
        layout {
            title = "관측지점별 일별 해수 정보"
            size = 800 to 400
        }

        ribbon {

            x("day") {
                axis.name = "측정일"
            }

            y.axis {
                limits = 2.0..15.0
                name = "수온 최저~최고"
            }

            yMin("min")
            yMax("max")
            fillColor("staNamKor"){
                legend {
                    name = "관측지점"
                }
            }
            alpha = 0.6
            borderLine.width = 0.0

            tooltips(title = value(staNamKor)){
                line("최저 ${value("min")}, 최고 ${value("max")}")
                line("측정일", day.tooltipValue("d"))
            }
        }


    }